"use client";

import { useMemo, useState } from "react";
import { ChevronRight, Filter, Plus, Search, SlidersHorizontal, X } from "lucide-react";
import type { Player, Role, Team } from "@/lib/types";
import type { ScoutingReport } from "@/lib/logic/scoutingAssignments";
import { getPlayerScoutingConfidence } from "@/lib/logic/scoutingAssignments";

type Scope = "season" | "ipl" | "t20";
type Op = "gte" | "lte" | "between" | "eq" | "contains";
type Condition = { id: number; key: string; op: Op; value: string; upper?: string };
type Filters = { ageGroup: string; role: "all" | Role; membership: string; scope: Scope; season: number; conditions: Condition[] };
type Meta = { key: string; label: string; category: string; type: "number" | "text" | "select"; hidden?: boolean; options?: string[]; defaultValue?: string };

const roles: Array<"all" | Role> = ["all", "Batsman", "WK-Batsman", "All-Rounder", "Pace Bowler", "Spin Bowler"];
const categories = ["Personal details", "Performance stats", "Attributes", "Hidden attributes"];
const metadata: Meta[] = [
  { category: "Personal details", key: "name", label: "Player name", type: "text", defaultValue: "" },
  { category: "Personal details", key: "state", label: "Indian state", type: "select" },
  { category: "Personal details", key: "country", label: "Country", type: "select" },
  { category: "Personal details", key: "team", label: "Current team", type: "select" },
  { category: "Personal details", key: "capped", label: "International status", type: "select", options: ["Capped", "Uncapped"] },
  { category: "Personal details", key: "battingStyle", label: "Batting hand", type: "select", options: ["Right-hand", "Left-hand"] },
  { category: "Personal details", key: "bowlingHand", label: "Bowling hand", type: "select", options: ["Right-hand", "Left-hand"] },
  { category: "Personal details", key: "bowlingStyle", label: "Bowling style", type: "select" },
  { category: "Personal details", key: "designation", label: "Playing designation", type: "select", options: ["Wicketkeeper", "Part-time keeper", "Opener", "Finisher", "Core batter"] },
  { category: "Performance stats", key: "matches", label: "Matches", type: "number", defaultValue: "5" },
  { category: "Performance stats", key: "runs", label: "Runs", type: "number", defaultValue: "100" },
  { category: "Performance stats", key: "wickets", label: "Wickets", type: "number", defaultValue: "5" },
  ...[["currentBatting", "Current batting"], ["currentBowling", "Current bowling"], ["potentialBatting", "Potential batting"], ["potentialBowling", "Potential bowling"], ["reputation", "Reputation"], ["basePrice", "Base price"]].map(([key, label]) => ({ category: "Attributes", key, label, type: "number" as const, defaultValue: "60" })),
  ...[["captaincy", "Captaincy"], ["battingAggression", "Batting aggression"], ["paceRating", "Pace batting"], ["spinRating", "Spin batting"], ["powerplayBatting", "Powerplay batting"], ["middleOversBatting", "Middle-over batting"], ["deathBatting", "Death-over batting"], ["powerplayBowling", "Powerplay bowling"], ["middleOversBowling", "Middle-over bowling"], ["deathBowling", "Death-over bowling"], ["stamina", "Batting consistency"], ["consistency", "Bowling consistency"], ["pressureRating", "Pressure"], ["bigMatchRating", "Big match"], ["injuryProneness", "Injury proneness"], ["fieldingRating", "Fielding"], ["wicketkeepingRating", "Wicketkeeping"]].map(([key, label]) => ({ category: "Hidden attributes", key, label, type: "number" as const, hidden: true, defaultValue: "60" })),
];
const defaultFilters = (season: number): Filters => ({ ageGroup: "all", role: "all", membership: "current", scope: "season", season, conditions: [] });
const control = "h-10 rounded-md border border-border bg-bg px-3 text-[12px] text-text-primary outline-none focus:border-accent";

export interface LeagueScoutingPageStat { matches?: number; runs?: number; wickets?: number; }
export interface LeagueScoutingPageProps { players: Record<string, Player>; teams: Record<string, Team>; userTeamId: string; currentSeason: number; currentSeasonStats: Record<string, LeagueScoutingPageStat>; scoutingReports: ScoutingReport[]; shortlist: string[]; onToggleShortlist: (id: string) => void; onAnalyse: (id: string) => void; }

export default function LeagueScoutingPage(props: LeagueScoutingPageProps) {
  const [query, setQuery] = useState("");
  const [modalOpen, setModalOpen] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const [applied, setApplied] = useState<Filters>(() => defaultFilters(props.currentSeason));
  const [draft, setDraft] = useState<Filters>(() => defaultFilters(props.currentSeason));
  const players = useMemo(() => Object.values(props.players).filter((p) => (p.iplHistory ?? []).some((h) => h.teamId && h.teamId !== "UNSOLD") || Boolean(p.currentTeamId && props.teams[p.currentTeamId])), [props.players, props.teams]);
  const seasons = useMemo(() => unique(players.flatMap((p) => (p.iplHistory ?? []).filter((h) => Boolean(h.seasonStats) && Number(h.season) < props.currentSeason).map((h) => String(h.season)))).sort((a, b) => Number(b) - Number(a)), [players, props.currentSeason]);
  const latestSimulatedSeason = Number(seasons[0] ?? props.currentSeason);
  const dynamicOptions = useMemo(() => ({ state: unique(players.map((p) => p.state)), country: unique(players.map((p) => p.country || p.nationality)), team: Object.values(props.teams).map((t) => t.name).sort(), bowlingStyle: unique(players.map((p) => p.bowlingStyle)) }), [players, props.teams]);
  const resolvedMeta = (key: string) => { const item = metadata.find((m) => m.key === key)!; return { ...item, options: item.options ?? dynamicOptions[key as keyof typeof dynamicOptions] }; };

  const results = useMemo(() => players.flatMap((player) => {
    if (query && !player.name.toLowerCase().includes(query.trim().toLowerCase())) return [];
    if (applied.role !== "all" && player.role !== applied.role) return [];
    if (applied.membership === "current" && !player.currentTeamId) return [];
    if (applied.membership === "former" && player.currentTeamId) return [];
    if (!ageMatches(player.age, applied.ageGroup)) return [];
    const confidence = player.currentTeamId === props.userTeamId ? 100 : getPlayerScoutingConfidence(props.scoutingReports, player.id);
    const seasonStats = applied.season === props.currentSeason ? props.currentSeasonStats[player.id] : (player.iplHistory ?? []).find((h) => Number(h.season) === applied.season)?.seasonStats;
    const stats = applied.scope === "season" ? { matches: seasonStats?.matches ?? 0, runs: seasonStats?.runs ?? 0, wickets: seasonStats?.wickets ?? 0 } : applied.scope === "ipl" ? { matches: player.iplStats.matches, runs: player.iplStats.runs, wickets: player.iplStats.wickets } : { matches: Math.max(player.careerStats.batting.matches, player.careerStats.bowling.matches), runs: player.careerStats.batting.runs, wickets: player.careerStats.bowling.wickets };
    for (const condition of applied.conditions) {
      const meta = metadata.find((m) => m.key === condition.key)!;
      if (meta.hidden && confidence < 100) continue;
      const actual = conditionValue(condition.key, player, stats, props.teams);
      if (!conditionMatches(actual, condition)) return [];
    }
    return [{ player, confidence, stats, ability: Math.max(player.currentBatting, player.currentBowling) }];
  }).sort((a, b) => b.ability - a.ability), [players, query, applied, props]);

  const openFilters = () => { const season = applied.scope === "season" && !seasons.includes(String(applied.season)) ? latestSimulatedSeason : applied.season; setDraft({ ...applied, season, conditions: applied.conditions.map((c) => ({ ...c })) }); setMenuOpen(false); setModalOpen(true); };
  const addCondition = (meta: Meta) => { setDraft((current) => ({ ...current, conditions: [...current.conditions, { id: Date.now() + Math.random(), key: meta.key, op: meta.type === "number" ? "gte" : meta.type === "text" ? "contains" : "eq", value: meta.defaultValue ?? meta.options?.[0] ?? dynamicOptions[meta.key as keyof typeof dynamicOptions]?.[0] ?? "" }] })); setMenuOpen(false); };
  const updateCondition = (id: number, patch: Partial<Condition>) => setDraft((current) => ({ ...current, conditions: current.conditions.map((c) => c.id === id ? { ...c, ...patch } : c) }));
  const search = () => { setApplied({ ...draft, conditions: draft.conditions.map((c) => ({ ...c })) }); setModalOpen(false); };
  const reset = () => { const clean = defaultFilters(latestSimulatedSeason); setApplied(clean); setDraft(clean); setQuery(""); };
  const preset = (key: string, statKey?: string) => { const conditions: Condition[] = [{ id: Date.now(), key, op: "gte", value: "70" }]; if (statKey) conditions.push({ id: Date.now() + 1, key: statKey, op: "gte", value: statKey === "runs" ? "150" : "8" }); setApplied({ ...defaultFilters(latestSimulatedSeason), conditions }); };
  const activeCount = applied.conditions.length + Number(applied.ageGroup !== "all") + Number(applied.role !== "all") + Number(applied.membership !== "current") + Number(applied.scope !== "season") + Number(applied.season !== props.currentSeason);

  return <div className="relative flex h-full min-h-0 flex-col gap-4 overflow-hidden p-6">
    <section className="shrink-0 rounded-xl border-2 border-border bg-surface shadow-sm">
      <div className="flex items-center justify-between border-b border-border px-5 py-4"><div><h2 className="font-anton text-[20px] uppercase">Find an IPL player</h2><p className="mt-1 text-[12px] text-text-secondary">Search league history and build a shortlist from the evidence you care about.</p></div><span className="rounded-full bg-accent/10 px-3 py-1.5 font-space-mono text-[10px] font-bold uppercase text-accent">{results.length} matches</span></div>
      <div className="flex items-center gap-2 border-b border-border/60 px-4 py-3"><span className="mr-1 text-[10px] font-bold uppercase text-text-secondary">Quick searches</span><Pill text="Finishers" click={() => preset("deathBatting", "runs")}/><Pill text="Powerplay batters" click={() => preset("powerplayBatting", "runs")}/><Pill text="Death bowlers" click={() => preset("deathBowling", "wickets")}/><Pill text="Elite fielders" click={() => preset("fieldingRating")}/></div>
      <div className="grid grid-cols-[minmax(15rem,1fr)_auto] gap-3 p-4"><label className="relative"><Search className="absolute left-3 top-3 size-4 text-text-secondary"/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search by player name" className={`${control} w-full pl-9`}/></label><button onClick={openFilters} className="flex h-10 items-center gap-2 rounded-md border border-accent bg-accent/10 px-4 text-[11px] font-bold text-accent"><SlidersHorizontal className="size-4"/> Detailed filters{activeCount ? ` (${activeCount})` : ""}</button></div>
      {activeCount > 0 && <div className="flex items-center gap-2 border-t border-border px-5 py-3 text-[10px]"><b className="uppercase text-text-secondary">Applied search</b>{applied.ageGroup !== "all" && <Tag text={`Age: ${applied.ageGroup}`}/>} {applied.role !== "all" && <Tag text={applied.role}/>} {applied.conditions.slice(0, 4).map((c) => <Tag key={c.id} text={`${metadata.find((m) => m.key === c.key)?.label} ${opLabel(c.op)} ${c.value}${c.op === "between" ? `–${c.upper}` : ""}`}/>)}{activeCount > 6 && <Tag text={`+${activeCount - 6} more`}/>}<button onClick={openFilters} className="ml-auto font-bold uppercase text-accent">Edit</button><button onClick={reset} className="font-bold uppercase text-danger">Clear</button></div>}
    </section>
    <Results results={results} props={props} reset={reset}/>

    {modalOpen && <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 p-5" onMouseDown={(e) => { if (e.target === e.currentTarget) setModalOpen(false); }}><section className="flex max-h-[82vh] w-full max-w-[780px] flex-col overflow-hidden rounded-md border border-border bg-surface shadow-2xl">
      <header className="flex h-14 shrink-0 items-center justify-between border-b border-border bg-[var(--ink)] px-5 text-bg"><div><h2 className="font-anton text-[18px] uppercase tracking-wide">Player search</h2><p className="text-[9px] opacity-65">EDIT SEARCH CONDITIONS</p></div><button onClick={() => setModalOpen(false)} className="grid size-8 place-items-center rounded border border-white/25 hover:bg-white/10"><X className="size-4"/></button></header>
      <div className="min-h-0 flex-1 overflow-y-auto p-4">
        <div className="mb-2 flex items-center justify-between border-b border-border pb-2"><span className="font-space-mono text-[9px] font-bold uppercase text-text-secondary">Match all of the following</span><span className="text-[9px] text-text-secondary">Players must satisfy every active row</span></div>
        <div className="overflow-hidden rounded border border-border bg-bg/20"><BasicRow label="Age"><select value={draft.ageGroup} onChange={(e) => setDraft((f) => ({ ...f, ageGroup: e.target.value }))} className={`${control} w-64`}><option value="all">All age groups</option><option value="u21">Under 21</option><option value="21-24">21–24</option><option value="25-29">25–29</option><option value="30-34">30–34</option><option value="35+">35 and over</option></select></BasicRow><BasicRow label="Playing role"><select value={draft.role} onChange={(e) => setDraft((f) => ({ ...f, role: e.target.value as Filters["role"] }))} className={`${control} w-64`}>{roles.map((r) => <option key={r} value={r}>{r === "all" ? "All playing roles" : r}</option>)}</select></BasicRow><BasicRow label="League status"><select value={draft.membership} onChange={(e) => setDraft((f) => ({ ...f, membership: e.target.value }))} className={`${control} w-64`}><option value="current">Current IPL players</option><option value="former">Former IPL players</option><option value="all">Current and former players</option></select></BasicRow><BasicRow label="Performance record"><div className="flex gap-2"><select value={draft.scope} onChange={(e) => setDraft((f) => ({ ...f, scope: e.target.value as Scope }))} className={`${control} w-44`}><option value="season">Selected season</option><option value="ipl">IPL career</option><option value="t20">T20 career</option></select>{draft.scope === "season" && <select value={draft.season} onChange={(e) => setDraft((f) => ({ ...f, season: Number(e.target.value) }))} className={`${control} w-32`}>{seasons.length ? seasons.map((s) => <option key={s}>{s}</option>) : <option disabled>No simulated seasons</option>}</select>}</div></BasicRow></div>

        <div className="mt-4 overflow-hidden rounded border border-border">{draft.conditions.length ? draft.conditions.map((condition) => { const meta = resolvedMeta(condition.key); return <div key={condition.id} className="grid min-h-14 grid-cols-[1.35fr_0.8fr_1fr_auto] items-center gap-2 border-b border-border/70 bg-surface px-3 py-2 last:border-0 hover:bg-bg/40"><div className="text-[11px] font-bold">{meta.label}{meta.hidden && <span className="ml-2 text-[8px] font-bold uppercase text-warning">Hidden</span>}<p className="font-space-mono text-[8px] font-normal uppercase text-text-secondary">{meta.category}</p></div>{meta.type === "number" ? <select value={condition.op} onChange={(e) => updateCondition(condition.id, { op: e.target.value as Op })} className={`${control} h-8`}><option value="gte">is at least</option><option value="lte">is at most</option><option value="between">is between</option></select> : <span className="px-3 text-[10px] text-text-secondary">{meta.type === "text" ? "contains" : "is"}</span>}<div className="flex gap-1">{meta.type === "select" ? <select value={condition.value} onChange={(e) => updateCondition(condition.id, { value: e.target.value })} className={`${control} h-8 w-full`}>{(meta.options ?? []).map((option) => <option key={option}>{option}</option>)}</select> : <input type={meta.type === "number" ? "number" : "text"} value={condition.value} onChange={(e) => updateCondition(condition.id, { value: e.target.value })} className={`${control} h-8 w-full`}/>} {condition.op === "between" && <input type="number" value={condition.upper ?? ""} onChange={(e) => updateCondition(condition.id, { upper: e.target.value })} className={`${control} h-8 w-20`}/>}</div><button onClick={() => setDraft((f) => ({ ...f, conditions: f.conditions.filter((c) => c.id !== condition.id) }))} className="grid size-8 place-items-center text-text-secondary hover:text-danger"><X className="size-3"/></button></div>; }) : <div className="flex h-16 items-center justify-center text-[10px] text-text-secondary">No additional conditions</div>}</div>
        <div className="relative mt-3 inline-block"><button onClick={() => setMenuOpen((v) => !v)} className="flex h-9 items-center gap-2 rounded border border-border bg-bg px-4 text-[10px] font-bold uppercase hover:border-accent hover:text-accent"><Plus className="size-3"/> Add condition</button>{menuOpen && <ConditionMenu add={addCondition}/>}</div>
      </div>
      <footer className="flex shrink-0 items-center justify-between border-t border-border bg-bg/50 px-4 py-3"><button onClick={() => setDraft(defaultFilters(latestSimulatedSeason))} className="text-[10px] font-bold uppercase text-danger">Clear conditions</button><div className="flex gap-2"><button onClick={() => setModalOpen(false)} className="rounded border border-border px-5 py-2 text-[10px] font-bold uppercase">Cancel</button><button onClick={search} className="rounded bg-accent px-7 py-2 text-[10px] font-bold uppercase text-white">Search</button></div></footer>
    </section></div>}
  </div>;
}

function ConditionMenu({ add }: { add: (meta: Meta) => void }) { return <div className="absolute bottom-11 left-0 z-20 w-52 rounded border border-border bg-surface p-1 shadow-xl">{categories.map((category) => <div key={category} className="group relative"><div className="flex cursor-default items-center justify-between rounded px-3 py-2 text-[10px] font-bold hover:bg-accent hover:text-white">{category}<ChevronRight className="size-3"/></div><div className="absolute bottom-0 left-[calc(100%_-_2px)] hidden max-h-72 w-52 overflow-y-auto rounded border border-border bg-surface p-1 shadow-xl group-hover:block">{metadata.filter((m) => m.category === category).map((meta) => <button key={meta.key} onClick={() => add(meta)} className="block w-full rounded px-3 py-2 text-left text-[10px] hover:bg-accent hover:text-white">{meta.label}</button>)}</div></div>)}</div>; }
function Results({ results, props, reset }: { results: Array<{ player: Player; confidence: number; stats: { matches: number; runs: number; wickets: number }; ability: number }>; props: LeagueScoutingPageProps; reset: () => void }) { return <section className="flex min-h-0 flex-1 flex-col overflow-hidden rounded-xl border-2 border-border bg-surface shadow-sm"><div className="grid grid-cols-[minmax(13rem,1.4fr)_8rem_7rem_12rem_11rem_9rem] gap-4 border-b border-border bg-bg/50 px-5 py-3 font-space-mono text-[9px] font-bold uppercase text-text-secondary"><span>Player</span><span>Role</span><span>Ability</span><span>Performance</span><span>Scouting knowledge</span><span/></div><div className="min-h-0 flex-1 overflow-y-auto">{results.map(({ player, ability, confidence, stats }) => <div key={player.id} className="grid min-h-16 grid-cols-[minmax(13rem,1.4fr)_8rem_7rem_12rem_11rem_9rem] items-center gap-4 border-b border-border/60 px-5 py-3 hover:bg-bg/40"><div><button onClick={() => props.onAnalyse(player.id)} className="text-left text-[14px] font-bold hover:text-accent">{player.name}</button><p className="text-[10px] text-text-secondary">{props.teams[player.currentTeamId ?? ""]?.name ?? "Former / unsold"} · Age {player.age}{player.state ? ` · ${player.state}` : ""}</p></div><span className="text-[11px] text-text-secondary">{player.role}</span><span className="font-anton text-[20px]">{confidence === 100 ? ability : "—"}</span><span className="text-[11px]"><b>{stats.matches}</b> Mts · <b>{stats.runs}</b> Rs · <b>{stats.wickets}</b> Ws</span><span className={`w-fit rounded-full px-2 py-1 text-[9px] font-bold uppercase ${confidence === 100 ? "bg-success/10 text-success" : confidence ? "bg-warning/10 text-warning" : "bg-bg text-text-secondary"}`}>{confidence === 100 ? "Verified" : confidence ? `${confidence}% scouted` : "Not scouted"}</span><div className="flex gap-2"><button onClick={() => props.onAnalyse(player.id)} className="rounded-md bg-[var(--ink)] px-3 py-2 text-[10px] font-bold uppercase text-bg">Analyse</button><button onClick={() => props.onToggleShortlist(player.id)} className="rounded-md border border-border px-3 py-2 font-bold">{props.shortlist.includes(player.id) ? "✓" : "+"}</button></div></div>)}{!results.length && <div className="flex h-full flex-col items-center justify-center text-text-secondary"><Filter className="mb-3 size-8 opacity-40"/><p>No players match this search</p><button onClick={reset} className="mt-2 text-[10px] font-bold uppercase text-accent">Clear search</button></div>}</div></section>; }
function conditionValue(key: string, p: Player, stats: { matches: number; runs: number; wickets: number }, teams: Record<string, Team>): string | number | boolean { if (key in stats) return stats[key as keyof typeof stats]; if (key === "country") return p.country || p.nationality; if (key === "team") return teams[p.currentTeamId ?? ""]?.name ?? ""; if (key === "capped") return p.isCapped ? "Capped" : "Uncapped"; if (key === "designation") return [[p.isWicketkeeper, "Wicketkeeper"], [p.isPartTimeWk, "Part-time keeper"], [p.isOpener, "Opener"], [p.isFinisher, "Finisher"], [p.isCoreBatter, "Core batter"]].filter(([active]) => active).map(([, name]) => name).join("|"); return p[key as keyof Player] as string | number | boolean; }
function conditionMatches(actual: string | number | boolean, condition: Condition) { if (condition.op === "contains") return String(actual ?? "").toLowerCase().includes(condition.value.toLowerCase()); if (condition.op === "eq") return String(actual ?? "").split("|").includes(condition.value); const a = Number(actual ?? 0), value = Number(condition.value || 0); if (condition.op === "gte") return a >= value; if (condition.op === "lte") return a <= value; return a >= value && a <= Number(condition.upper || value); }
function ageMatches(age: number, group: string) { return group === "all" || (group === "u21" && age < 21) || (group === "21-24" && age >= 21 && age <= 24) || (group === "25-29" && age >= 25 && age <= 29) || (group === "30-34" && age >= 30 && age <= 34) || (group === "35+" && age >= 35); }
function unique(values: Array<string | null | undefined>) { return Array.from(new Set(values.filter((v): v is string => Boolean(v)))).sort(); }
function opLabel(op: Op) { return op === "gte" ? "≥" : op === "lte" ? "≤" : op === "between" ? "between" : op === "contains" ? "contains" : "is"; }
function Pill({ text, click }: { text: string; click: () => void }) { return <button onClick={click} className="rounded-full border border-border px-3 py-1.5 text-[10px] font-semibold hover:border-accent hover:text-accent">{text}</button>; }
function Tag({ text }: { text: string }) { return <span className="rounded bg-accent/10 px-2 py-1 font-semibold text-accent">{text}</span>; }
function BasicRow({ label, children }: { label: string; children: React.ReactNode }) { return <div className="grid min-h-12 grid-cols-[180px_1fr] items-center border-b border-border/70 px-3 py-1.5 last:border-0"><span className="text-[11px] font-bold">{label}</span>{children}</div>; }
function Select({ label, value, change, options }: { label: string; value: string; change: (value: string) => void; options: string[][] }) { return <label><span className="mb-1.5 block font-space-mono text-[9px] font-bold uppercase text-text-secondary">{label}</span><select value={value} onChange={(e) => change(e.target.value)} className={`${control} w-full`}>{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label>; }
