-- Approved 2026 starting roster: 108 bidirectional player pairs, 81 bidirectional player/staff pairs,
-- 43 staff pairs and 16 one-way idol links (248 rows total).
-- Generated from lib/data/personDynamicsSeeds.ts. Re-running is safe.

create temp table _person_dynamics_seed (
  category text not null,
  dynamic_type text not null,
  person1_key text not null,
  person2_key text not null,
  rating integer not null,
  is_bidirectional boolean not null,
  reason text not null,
  evidence_url text not null
);

insert into _person_dynamics_seed values
  ('player_player', 'opening_partners', 'Travis Head', 'Abhishek Sharma', 94, true, 'Established Sunrisers Hyderabad opening partnership.', 'https://www.iplt20.com/news/article/tata-ipl-2025-match-27-srh-vs-pbks-match-report'),
  ('player_player', 'opening_partners', 'Shubman Gill', 'Sai Sudharsan', 94, true, 'Established Gujarat Titans opening partnership.', 'https://www.iplt20.com/news/article/tata-ipl-2025-match-60-dc-vs-gt-match-report'),
  ('player_player', 'opening_partners', 'Devon Conway', 'Ruturaj Gaikwad', 86, true, 'Longstanding Chennai Super Kings opening partnership.', 'https://www.iplt20.com/teams/chennai-super-kings'),
  ('player_player', 'opening_partners', 'Jos Buttler', 'Yashasvi Jaiswal', 83, true, 'Former Rajasthan Royals opening partnership.', 'https://www.iplt20.com/news/article/tata-ipl-2024-match-38-rr-vs-mi-match-report'),
  ('player_player', 'mentor_protege', 'MS Dhoni', 'Ruturaj Gaikwad', 96, true, 'Long Chennai tenure together and Dhoni''s captaincy handover to Gaikwad.', 'https://www.iplt20.com/news/article/ruturaj-gaikwad-takes-over-chennai-super-kings-captaincy-from-ms-dhoni'),
  ('player_player', 'franchise_teammates', 'MS Dhoni', 'Ravindra Jadeja', 88, true, 'Longstanding Chennai Super Kings core players.', 'https://www.iplt20.com/teams/chennai-super-kings'),
  ('player_player', 'mentor_protege', 'Sanju Samson', 'Riyan Parag', 91, true, 'Parag has described Samson''s support and influence on his game.', 'https://www.rajasthanroyals.com/latest-news/on-the-field-you-learn-a-lot-from-him---parag-underlines-sanju-samsons-influence-on-his-game'),
  ('player_player', 'franchise_teammates', 'Sanju Samson', 'Yashasvi Jaiswal', 78, true, 'Multiple Rajasthan Royals seasons in the same batting group.', 'https://www.rajasthanroyals.com/static-assets/pdfs/IPL-2024.pdf'),
  ('player_player', 'spin_twins', 'Sunil Narine', 'Varun Chakravarthy', 90, true, 'Established Kolkata Knight Riders spin pairing.', 'https://www.iplt20.com/news/article/tata-ipl-2023-match-09-kkr-vs-rcb-match-report'),
  ('player_player', 'spin_twins', 'Axar Patel', 'Kuldeep Yadav', 84, true, 'Delhi Capitals spin pairing across multiple seasons.', 'https://www.iplt20.com/teams/delhi-capitals'),
  ('player_player', 'franchise_teammates', 'Rishabh Pant', 'Axar Patel', 83, true, 'Longstanding Delhi captain and senior all-rounder partnership.', 'https://www.iplt20.com/news/3982/hardik-pandya-and-cameron-green-traded-to-mi-and-rcbWhatareyourthoughtsonthistrade'),
  ('player_player', 'franchise_teammates', 'Virat Kohli', 'Rajat Patidar', 78, true, 'Repeated Royal Challengers Bengaluru seasons together, including Patidar''s captaincy.', 'https://royalchallengers.com/rcb-cricket-news/news/rcb-podcast-mo-bobat-reveals-how-rajat-patidar-was-picked-as-captain-ahead-of'),
  ('player_player', 'franchise_teammates', 'Rohit Sharma', 'Jasprit Bumrah', 88, true, 'Longstanding Mumbai Indians captain and lead bowler partnership.', 'https://www.mumbaiindians.com/amp/news/jasprit-bumrah-blue-blood-death-bowling'),
  ('player_player', 'franchise_teammates', 'Rohit Sharma', 'Suryakumar Yadav', 81, true, 'Longstanding Mumbai Indians batting group.', 'https://www.mumbaiindians.com/'),
  ('player_player', 'franchise_teammates', 'Suryakumar Yadav', 'Tilak Varma', 79, true, 'Several Mumbai Indians seasons in the middle order.', 'https://www.mumbaiindians.com/'),
  ('player_player', 'spin_twins', 'Rashid Khan', 'Noor Ahmad', 87, true, 'Afghanistan and former Gujarat Titans spin pairing.', 'https://www.iplt20.com/video/49636/on-the-mic-with-spin-twins-rashid-khan-noor-ahmad'),
  ('player_player', 'spin_twins', 'Kuldeep Yadav', 'Yuzvendra Chahal', 88, true, 'Established India wrist-spin pairing.', 'https://www.bcci.tv/'),
  ('player_player', 'pace_tandem', 'Jasprit Bumrah', 'Mohammed Shami', 78, true, 'India pace attack across major tournaments.', 'https://www.bcci.tv/'),
  ('player_player', 'national_teammates', 'Virat Kohli', 'Rohit Sharma', 85, true, 'Long tenure together in India''s senior batting group.', 'https://www.bcci.tv/'),
  ('player_player', 'franchise_teammates', 'Travis Head', 'Pat Cummins', 77, true, 'Australia teammates and Sunrisers Hyderabad senior players.', 'https://www.iplt20.com/teams/sunrisers-hyderabad'),
  ('player_player', 'franchise_teammates', 'Rinku Singh', 'Venkatesh Iyer', 75, true, 'Multiple Kolkata Knight Riders seasons together.', 'https://www.iplt20.com/teams/kolkata-knight-riders'),
  ('player_player', 'franchise_teammates', 'Shubman Gill', 'Rashid Khan', 77, true, 'Senior Gujarat Titans teammates through Gill''s captaincy.', 'https://www.gujarattitansipl.com/news/gujarat-titans-gt-tata-ipl-2026-pre-season-press-conference'),
  ('player_player', 'opening_partners', 'Rohit Sharma', 'Ishan Kishan', 88, true, 'Established Mumbai Indians multi-season opening batting combination.', 'https://www.mumbaiindians.com/'),
  ('player_player', 'opening_partners', 'Phil Salt', 'Sunil Narine', 91, true, 'Explosive title-winning opening pair for Kolkata Knight Riders in 2024.', 'https://www.iplt20.com/teams/kolkata-knight-riders'),
  ('player_player', 'opening_partners', 'KL Rahul', 'Quinton De Kock', 87, true, 'Prolific opening pair for Lucknow Super Giants across multiple campaigns.', 'https://www.lucknowsupergiants.in/'),
  ('player_player', 'opening_partners', 'Ruturaj Gaikwad', 'Rachin Ravindra', 84, true, 'Chennai Super Kings opening combination following Conway''s injury.', 'https://www.iplt20.com/teams/chennai-super-kings'),
  ('player_player', 'pace_tandem', 'Trent Boult', 'Jasprit Bumrah', 92, true, 'Devastating Mumbai Indians opening bowling partnership during title runs.', 'https://www.mumbaiindians.com/'),
  ('player_player', 'pace_tandem', 'Trent Boult', 'Sandeep Sharma', 85, true, 'Complementary Rajasthan Royals new-ball and death-overs pace strike pair.', 'https://www.rajasthanroyals.com/'),
  ('player_player', 'pace_tandem', 'Mohammed Siraj', 'Jasprit Bumrah', 86, true, 'Frontline India national team fast-bowling tandem across all formats.', 'https://www.bcci.tv/'),
  ('player_player', 'pace_tandem', 'Arshdeep Singh', 'Kagiso Rabada', 84, true, 'Primary fast bowling strike pair for Punjab Kings across consecutive seasons.', 'https://www.punjabkingsipl.in/'),
  ('player_player', 'pace_tandem', 'Pat Cummins', 'Bhuvneshwar Kumar', 83, true, 'Experienced senior Sunrisers Hyderabad pace attack leaders.', 'https://www.sunrisershyderabad.in/'),
  ('player_player', 'pace_tandem', 'Harshit Rana', 'Mitchell Starc', 85, true, 'Title-winning Kolkata Knight Riders pace duo in 2024 IPL campaign.', 'https://www.iplt20.com/teams/kolkata-knight-riders'),
  ('player_player', 'pace_tandem', 'Khaleel Ahmed', 'Mukesh Kumar', 81, true, 'Consistent Indian pace duo leading the Delhi Capitals bowling attack.', 'https://www.delhicapitals.in/'),
  ('player_player', 'pace_tandem', 'Mohammed Shami', 'Mohammed Siraj', 85, true, 'Experienced senior pace strike partners for the Indian national team.', 'https://www.bcci.tv/'),
  ('player_player', 'pace_tandem', 'Anrich Nortje', 'Kagiso Rabada', 88, true, 'Lethal South African express pace duo who also spearheaded Delhi Capitals attack.', 'https://www.delhicapitals.in/'),
  ('player_player', 'pace_tandem', 'Matheesha Pathirana', 'Tushar Deshpande', 82, true, 'Chennai Super Kings frontline death and middle-overs seam attack.', 'https://www.iplt20.com/teams/chennai-super-kings'),
  ('player_player', 'pace_tandem', 'Akash Deep', 'Mohammed Siraj', 79, true, 'Shared new ball duties for Royal Challengers Bengaluru and India Test attack.', 'https://www.royalchallengers.com/'),
  ('player_player', 'spin_twins', 'Ravi Bishnoi', 'Krunal Pandya', 82, true, 'Tightly-knit spin bowling tandem controlling the middle overs for Lucknow Super Giants.', 'https://www.lucknowsupergiants.in/'),
  ('player_player', 'spin_twins', 'Ravindra Jadeja', 'Maheesh Theekshana', 83, true, 'Complementary finger-spin and mystery-spin pairing for Chennai Super Kings.', 'https://www.iplt20.com/teams/chennai-super-kings'),
  ('player_player', 'spin_twins', 'Ravindra Jadeja', 'Axar Patel', 84, true, 'National left-arm orthodox spin and all-round tandem for India.', 'https://www.bcci.tv/'),
  ('player_player', 'spin_twins', 'R. Sai Kishore', 'Rashid Khan', 81, true, 'Sustained spin combination for Gujarat Titans through playoff runs.', 'https://www.gujarattitansipl.com/'),
  ('player_player', 'spin_twins', 'Rahul Chahar', 'Harpreet Brar', 80, true, 'Primary spin pairing for Punjab Kings across multiple seasons.', 'https://www.punjabkingsipl.in/'),
  ('player_player', 'spin_twins', 'Mayank Markande', 'Shahbaz Ahmed', 78, true, 'Spin bowling duo for Sunrisers Hyderabad during the 2024 campaign.', 'https://www.sunrisershyderabad.in/'),
  ('player_player', 'spin_twins', 'Suyash Sharma', 'Varun Chakravarthy', 80, true, 'Part of Kolkata Knight Riders mystery spin attack unit.', 'https://www.iplt20.com/teams/kolkata-knight-riders'),
  ('player_player', 'mentor_protege', 'Rohit Sharma', 'Tilak Varma', 88, true, 'Rohit took Tilak under his wing as Mumbai Indians groom him for top-order leadership.', 'https://www.mumbaiindians.com/'),
  ('player_player', 'mentor_protege', 'Virat Kohli', 'Mohammed Siraj', 92, true, 'Kohli backed Siraj through career-defining early struggles at RCB to become an international spearhead.', 'https://www.royalchallengers.com/'),
  ('player_player', 'mentor_protege', 'MS Dhoni', 'Shivam Dube', 90, true, 'Dhoni unlocked Dube''s game by defining his spin-hitting middle-overs role at Chennai Super Kings.', 'https://www.iplt20.com/teams/chennai-super-kings'),
  ('player_player', 'mentor_protege', 'MS Dhoni', 'Matheesha Pathirana', 91, true, 'Dhoni closely mentored Pathirana''s death bowling development and workload management at CSK.', 'https://www.iplt20.com/teams/chennai-super-kings'),
  ('player_player', 'mentor_protege', 'Rohit Sharma', 'Ishan Kishan', 85, true, 'Rohit continuously guided Kishan through batting form and wicketkeeping responsibilities at Mumbai Indians.', 'https://www.mumbaiindians.com/'),
  ('player_player', 'mentor_protege', 'Ravindra Jadeja', 'Rachin Ravindra', 82, true, 'Jadeja guides the young Kiwi all-rounder within the CSK setup and international circuit.', 'https://www.iplt20.com/teams/chennai-super-kings'),
  ('player_player', 'mentor_protege', 'Suryakumar Yadav', 'Nehal Wadhera', 83, true, 'Suryakumar actively mentors Wadhera''s 360-degree boundary hitting and game awareness at MI.', 'https://www.mumbaiindians.com/'),
  ('player_player', 'mentor_protege', 'Hardik Pandya', 'Tilak Varma', 80, true, 'Pandya works closely with Varma on middle-order finishing under pressure.', 'https://www.mumbaiindians.com/'),
  ('player_player', 'mentor_protege', 'Jasprit Bumrah', 'Akash Madhwal', 84, true, 'Bumrah worked directly with Madhwal on yorker execution and death bowling composure at MI.', 'https://www.mumbaiindians.com/'),
  ('player_player', 'mentor_protege', 'Jasprit Bumrah', 'Gerald Coetzee', 81, true, 'Bumrah guides the young South African tearaway in the Mumbai Indians pace attack.', 'https://www.mumbaiindians.com/'),
  ('player_player', 'mentor_protege', 'Pat Cummins', 'Nitish Kumar Reddy', 85, true, 'Cummins heavily backed and empowered young all-rounder Nitish Reddy during SRH''s 2024 run.', 'https://www.sunrisershyderabad.in/'),
  ('player_player', 'mentor_protege', 'Sunil Narine', 'Angkrish Raghuvanshi', 79, true, 'Narine guides the youngster in handling high-tempo batting at Kolkata Knight Riders.', 'https://www.iplt20.com/teams/kolkata-knight-riders'),
  ('player_player', 'domestic_roots', 'Shreyas Iyer', 'Suryakumar Yadav', 88, true, 'Grew up together through Mumbai maidans and domestic cricket setup (Ranji Trophy).', 'https://www.mumbaicricket.com/'),
  ('player_player', 'domestic_roots', 'Rohit Sharma', 'Shardul Thakur', 86, true, 'Longstanding Mumbai domestic teammates and Ranji Trophy champions.', 'https://www.mumbaicricket.com/'),
  ('player_player', 'domestic_roots', 'Hardik Pandya', 'Krunal Pandya', 98, true, 'Brothers who rose through Baroda domestic cricket and Mumbai Indians together.', 'https://www.bcci.tv/'),
  ('player_player', 'domestic_roots', 'Sarfaraz Khan', 'Musheer Khan', 96, true, 'Brothers who trained together under father Naushad Khan and star for Mumbai domestic cricket.', 'https://www.mumbaicricket.com/'),
  ('player_player', 'domestic_roots', 'Shubman Gill', 'Arshdeep Singh', 89, true, 'Came through Punjab junior and senior age-group cricket together.', 'https://www.bcci.tv/'),
  ('player_player', 'domestic_roots', 'Abhishek Sharma', 'Arshdeep Singh', 87, true, 'Longtime Punjab domestic teammates and U19 state compatriots.', 'https://www.bcci.tv/'),
  ('player_player', 'domestic_roots', 'Prithvi Shaw', 'Sarfaraz Khan', 85, true, 'Childhood Mumbai school and domestic cricket batting prodigies.', 'https://www.mumbaicricket.com/'),
  ('player_player', 'domestic_roots', 'Ruturaj Gaikwad', 'Rahul Tripathi', 83, true, 'Longtime Maharashtra Ranji Trophy batting mainstays.', 'https://www.bcci.tv/'),
  ('player_player', 'domestic_roots', 'Rinku Singh', 'Dhruv Jurel', 84, true, 'Uttar Pradesh domestic teammates sharing a close journey through state cricket.', 'https://www.bcci.tv/'),
  ('player_player', 'domestic_roots', 'Yashasvi Jaiswal', 'Sarfaraz Khan', 84, true, 'Mumbai domestic batting linchpins who shared massive Ranji Trophy partnerships.', 'https://www.mumbaicricket.com/'),
  ('player_player', 'domestic_roots', 'Tilak Varma', 'Nitish Kumar Reddy', 81, true, 'Hyderabad and Andhra South Zone domestic circuit peers from junior cricket.', 'https://www.bcci.tv/'),
  ('player_player', 'domestic_roots', 'R. Sai Kishore', 'Shahrukh Khan', 84, true, 'Tamil Nadu domestic champions who won multiple Syed Mushtaq Ali Trophy titles together.', 'https://www.bcci.tv/'),
  ('player_player', 'domestic_roots', 'R. Sai Kishore', 'Washington Sundar', 82, true, 'Tamil Nadu spin-bowling all-round compatriots since age-group cricket.', 'https://www.bcci.tv/'),
  ('player_player', 'personal_bond', 'KL Rahul', 'Hardik Pandya', 90, true, 'Extremely close personal friendship off the pitch spanning many years.', 'https://www.bcci.tv/'),
  ('player_player', 'personal_bond', 'Ishan Kishan', 'Rishabh Pant', 89, true, 'Close friends since India U19 World Cup 2016 campaign.', 'https://www.bcci.tv/'),
  ('player_player', 'personal_bond', 'Shubman Gill', 'Ishan Kishan', 88, true, 'Close camaraderie and well-documented bonding on and off national tours.', 'https://www.bcci.tv/'),
  ('player_player', 'personal_bond', 'Sanju Samson', 'Shimron Hetmyer', 84, true, 'Close personal friendship and mutual admiration forged at Rajasthan Royals.', 'https://www.rajasthanroyals.com/'),
  ('player_player', 'personal_bond', 'Rinku Singh', 'Nitish Rana', 86, true, 'Deep friendship developed through Kolkata Knight Riders seasons.', 'https://www.iplt20.com/teams/kolkata-knight-riders'),
  ('player_player', 'personal_bond', 'Axar Patel', 'Rishabh Pant', 87, true, 'Longstanding close bond on and off the field for Delhi Capitals and India.', 'https://www.delhicapitals.in/'),
  ('player_player', 'franchise_teammates', 'Hardik Pandya', 'Jasprit Bumrah', 86, true, 'Foundational pillars of Mumbai Indians'' multi-trophy dominance.', 'https://www.mumbaiindians.com/'),
  ('player_player', 'franchise_teammates', 'Hardik Pandya', 'Rohit Sharma', 84, true, 'Longtime core Mumbai Indians stars sharing multiple championship celebrations.', 'https://www.mumbaiindians.com/'),
  ('player_player', 'franchise_teammates', 'Heinrich Klaasen', 'Travis Head', 86, true, 'Explosive middle-order and top-order backbone of Sunrisers Hyderabad''s record totals.', 'https://www.sunrisershyderabad.in/'),
  ('player_player', 'franchise_teammates', 'Pat Cummins', 'Heinrich Klaasen', 85, true, 'Captain and premier match-winner core at Sunrisers Hyderabad.', 'https://www.sunrisershyderabad.in/'),
  ('player_player', 'franchise_teammates', 'Nicholas Pooran', 'KL Rahul', 84, true, 'Senior batting leaders for Lucknow Super Giants across consecutive seasons.', 'https://www.lucknowsupergiants.in/'),
  ('player_player', 'franchise_teammates', 'Nicholas Pooran', 'Ayush Badoni', 80, true, 'Middle-order batting partners finishing high-pressure chases for LSG.', 'https://www.lucknowsupergiants.in/'),
  ('player_player', 'franchise_teammates', 'Jos Buttler', 'Sanju Samson', 90, true, 'Foundational senior batting leaders for Rajasthan Royals across six seasons.', 'https://www.rajasthanroyals.com/'),
  ('player_player', 'franchise_teammates', 'Riyan Parag', 'Shimron Hetmyer', 82, true, 'Finishing duo who have sealed multiple tense finishes for Rajasthan Royals.', 'https://www.rajasthanroyals.com/'),
  ('player_player', 'franchise_teammates', 'Rahul Tewatia', 'Rashid Khan', 85, true, 'Legendary finishing duo who produced miraculous final-over heists for Gujarat Titans.', 'https://www.gujarattitansipl.com/'),
  ('player_player', 'franchise_teammates', 'Shashank Singh', 'Ashutosh Sharma', 88, true, 'Breakout dynamic finishing duo for Punjab Kings in 2024 who repeatedly turned games.', 'https://www.punjabkingsipl.in/'),
  ('player_player', 'franchise_teammates', 'Tristan Stubbs', 'Rishabh Pant', 82, true, 'Key middle-order batting pillars for Delhi Capitals.', 'https://www.delhicapitals.in/'),
  ('player_player', 'franchise_teammates', 'Tristan Stubbs', 'Axar Patel', 80, true, 'Lower-middle order game changers for Delhi Capitals in 2024.', 'https://www.delhicapitals.in/'),
  ('player_player', 'franchise_teammates', 'Shivam Dube', 'Ravindra Jadeja', 83, true, 'Core middle-order and finishing all-rounders for Chennai Super Kings.', 'https://www.iplt20.com/teams/chennai-super-kings'),
  ('player_player', 'franchise_teammates', 'Deepak Chahar', 'Shardul Thakur', 84, true, 'Longtime Indian seam bowling core for Chennai Super Kings across title wins.', 'https://www.iplt20.com/teams/chennai-super-kings'),
  ('player_player', 'franchise_teammates', 'Harshal Patel', 'Mohammed Siraj', 82, true, 'Pace attack partners during Royal Challengers Bengaluru''s playoff campaigns.', 'https://www.royalchallengers.com/'),
  ('player_player', 'national_teammates', 'Rohit Sharma', 'Hardik Pandya', 86, true, 'Captain and vice-captain tandem who led India to the 2024 T20 World Cup triumph.', 'https://www.bcci.tv/'),
  ('player_player', 'national_teammates', 'Virat Kohli', 'Hardik Pandya', 85, true, 'Senior match-winners who orchestrated famous international chases for India.', 'https://www.bcci.tv/'),
  ('player_player', 'national_teammates', 'Virat Kohli', 'Jasprit Bumrah', 89, true, 'World-class batting and bowling superstars who anchored India across a decade of cricket.', 'https://www.bcci.tv/'),
  ('player_player', 'national_teammates', 'Rohit Sharma', 'Ravindra Jadeja', 87, true, 'Longstanding senior India stalwarts across Test, ODI and T20 World Cup squads.', 'https://www.bcci.tv/'),
  ('player_player', 'national_teammates', 'Virat Kohli', 'Ravindra Jadeja', 88, true, 'Teammates since the 2008 U19 World Cup win through senior Indian dominance.', 'https://www.bcci.tv/'),
  ('player_player', 'national_teammates', 'Suryakumar Yadav', 'Hardik Pandya', 85, true, 'India T20I leadership core and middle-order power hitters.', 'https://www.bcci.tv/'),
  ('player_player', 'national_teammates', 'Jos Buttler', 'Sam Curran', 84, true, 'England T20 World Cup title-winning captain and player of the tournament duo.', 'https://www.ecb.co.uk/'),
  ('player_player', 'national_teammates', 'Pat Cummins', 'Travis Head', 88, true, 'Australia World Cup winning leaders and Ashes stalwarts.', 'https://www.cricket.com.au/'),
  ('player_player', 'national_teammates', 'Pat Cummins', 'Mitchell Starc', 92, true, 'Longstanding Australia pace strike spearheads across all formats.', 'https://www.cricket.com.au/'),
  ('player_player', 'national_teammates', 'Pat Cummins', 'Josh Hazlewood', 90, true, 'Australia''s legendary pace attack foundation.', 'https://www.cricket.com.au/'),
  ('player_player', 'national_teammates', 'Mitchell Starc', 'Josh Hazlewood', 89, true, 'Australia frontline strike pace partners for over a decade.', 'https://www.cricket.com.au/'),
  ('player_player', 'national_teammates', 'Rashid Khan', 'Fazalhaq Farooqi', 86, true, 'Afghanistan senior bowling spearheads leading historic World Cup runs.', 'https://www.icc-cricket.com/'),
  ('player_player', 'national_teammates', 'Rashid Khan', 'Rahmanullah Gurbaz', 87, true, 'Talismanic leaders of Afghanistan''s explosive white-ball squad.', 'https://www.icc-cricket.com/'),
  ('player_player', 'national_teammates', 'Heinrich Klaasen', 'David Miller', 87, true, 'South Africa''s fearsome middle-order match-winning finishing core.', 'https://cricket.co.za/'),
  ('player_player', 'national_teammates', 'Kagiso Rabada', 'Anrich Nortje', 88, true, 'South Africa''s elite strike fast-bowling tandem.', 'https://cricket.co.za/'),
  ('player_player', 'national_teammates', 'Quinton De Kock', 'David Miller', 86, true, 'Veteran South African white-ball pillars across multiple World Cups.', 'https://cricket.co.za/'),
  ('player_player', 'national_teammates', 'Wanindu Hasaranga', 'Maheesh Theekshana', 86, true, 'Sri Lanka''s twin spin bowling strike force across international tournaments.', 'https://www.srilankacricket.lk/'),
  ('player_player', 'national_teammates', 'Phil Salt', 'Harry Brook', 83, true, 'England aggressive new-generation white-ball batting group.', 'https://www.ecb.co.uk/'),
  ('player_staff', 'specialist_tutelage', 'Jasprit Bumrah', 'lasith-malinga', 96, true, 'Malinga mentored Bumrah''s bowling at Mumbai Indians.', 'https://www.mumbaiindians.com/amp/news/jasprit-bumrah-blue-blood-death-bowling'),
  ('player_staff', 'specialist_tutelage', 'Jasprit Bumrah', 'shane-bond', 89, true, 'Bond coached Mumbai''s bowling during Bumrah''s development.', 'https://www.mumbaiindians.com/news/brain-behind-bowling'),
  ('player_staff', 'captain_coach_synergy', 'MS Dhoni', 'stephen-fleming', 98, true, 'Exceptionally long Chennai captain and coach partnership.', 'https://www.iplt20.com/news/article/msd-excellent-reader-of-the-game-fleming'),
  ('player_staff', 'captain_coach_synergy', 'Ruturaj Gaikwad', 'stephen-fleming', 88, true, 'Fleming coached Gaikwad through his move into Chennai captaincy.', 'https://www.iplt20.com/news/article/ruturaj-gaikwad-takes-over-chennai-super-kings-captaincy-from-ms-dhoni'),
  ('player_staff', 'captain_coach_synergy', 'Rishabh Pant', 'ricky-ponting', 88, true, 'Former Delhi captain and head coach partnership.', 'https://www.delhicapitals.in/news/ajit-agarkar-joins-delhi-capitals-as-assistant-coach'),
  ('player_staff', 'captain_coach_synergy', 'Shreyas Iyer', 'ricky-ponting', 90, true, 'Reunited as Punjab captain and head coach after working together at Delhi.', 'https://www.punjabkingsipl.in/features/shreyas-iyer-to-lead-punjab-kings'),
  ('player_staff', 'captain_coach_synergy', 'Rajat Patidar', 'andy-flower', 88, true, 'Bengaluru captain and head coach; Flower publicly backed Patidar''s leadership.', 'https://royalchallengers.com/rcb-cricket-news/news/rajats-got-a-stubbornness-and-a-strength-and-a-steeliness-about-him-andy'),
  ('player_staff', 'coached', 'Virat Kohli', 'andy-flower', 76, true, 'Shared Royal Challengers Bengaluru coaching tenure.', 'https://www.royalchallengers.com/'),
  ('player_staff', 'coached', 'Riyan Parag', 'kumar-sangakkara', 91, true, 'Parag credits Sangakkara''s coaching and support during his development.', 'https://www.rajasthanroyals.com/latest-news/on-the-field-you-learn-a-lot-from-him---parag-underlines-sanju-samsons-influence-on-his-game'),
  ('player_staff', 'captain_coach_synergy', 'Sanju Samson', 'kumar-sangakkara', 87, true, 'Former Rajasthan captain and cricket leader partnership.', 'https://www.rajasthanroyals.com/static-assets/pdfs/royals-scoop-ipl-2024.pdf'),
  ('player_staff', 'captain_coach_synergy', 'Shubman Gill', 'ashish-nehra', 90, true, 'Gujarat Titans captain and head coach partnership.', 'https://www.gujarattitansipl.com/news/gujarat-titans-gt-tata-ipl-2026-pre-season-press-conference'),
  ('player_staff', 'captain_coach_synergy', 'Hardik Pandya', 'ashish-nehra', 86, true, 'Former Gujarat Titans title-winning captain and head coach partnership.', 'https://www.gujarattitansipl.com/news/season-of-firsts-begins-five-things-we-are-most-excited-about-in-our-debut-season'),
  ('player_staff', 'captain_coach_synergy', 'Rohit Sharma', 'mahela-jayawardene', 88, true, 'Mumbai captain and head coach through multiple title-winning seasons.', 'https://www.mumbaiindians.com/news/welcome-back-head-coach-mahela-jayawardene-ipl-2025'),
  ('player_staff', 'captain_coach_synergy', 'Hardik Pandya', 'mahela-jayawardene', 82, true, 'Mumbai captain and returning head coach.', 'https://www.mumbaiindians.com/news/welcome-back-head-coach-mahela-jayawardene-ipl-2025'),
  ('player_staff', 'specialist_tutelage', 'Abhishek Sharma', 'yuvraj-singh', 95, true, 'Sustained individual batting mentorship.', 'https://www.hindustantimes.com/htcity/abhishek-sharma-on-comparisons-with-yuvraj-singh-he-taught-me-how-to-be-fearless-an-honour-to-have-him-as-my-mentor-101738671077665-amp.html'),
  ('player_staff', 'captain_coach_synergy', 'Virat Kohli', 'ravi-shastri', 88, true, 'Long India captain and head coach partnership.', 'https://www.bcci.tv/news/article/most-challenging-satisfying-job-ive-had-shastri'),
  ('player_staff', 'former_teammates', 'Sunil Narine', 'gautam-gambhir', 86, true, 'Former Kolkata teammates; Gambhir backed Narine as an opener.', 'https://www.iplt20.com/news/article/need-to-take-batting-tips-from-narine-gambhir'),
  ('player_staff', 'coached', 'Rinku Singh', 'gautam-gambhir', 80, true, 'Gambhir mentored Kolkata during Rinku''s tenure.', 'https://www.iplt20.com/teams/kolkata-knight-riders'),
  ('player_staff', 'captain_coach_synergy', 'Pat Cummins', 'daniel-vettori', 92, true, 'Highly successful captain and head coach partnership that took Sunrisers Hyderabad to the 2024 final.', 'https://www.sunrisershyderabad.in/'),
  ('player_staff', 'captain_coach_synergy', 'Shreyas Iyer', 'chandrakant-pandit', 88, true, 'Captain and head coach pairing that delivered Kolkata Knight Riders the 2024 IPL trophy.', 'https://www.iplt20.com/teams/kolkata-knight-riders'),
  ('player_staff', 'captain_coach_synergy', 'KL Rahul', 'justin-langer', 82, true, 'Captain and head coach leadership trust at Lucknow Super Giants.', 'https://www.lucknowsupergiants.in/'),
  ('player_staff', 'captain_coach_synergy', 'Sanju Samson', 'rahul-dravid', 90, true, 'Samson reunites with Dravid at Rajasthan Royals after Dravid originally drafted and nurtured him.', 'https://www.rajasthanroyals.com/'),
  ('player_staff', 'captain_coach_synergy', 'Ruturaj Gaikwad', 'dwayne-bravo', 83, true, 'Gaikwad leads CSK on field with Bravo managing bowling plans in the dugout.', 'https://www.iplt20.com/teams/chennai-super-kings'),
  ('player_staff', 'captain_coach_synergy', 'Axar Patel', 'ricky-ponting', 84, true, 'Ponting elevated Axar to vice-captain and strategic sounding board at Delhi Capitals.', 'https://www.delhicapitals.in/'),
  ('player_staff', 'specialist_tutelage', 'Varun Chakravarthy', 'carl-crowe', 90, true, 'Crowe worked intensively with Chakravarthy on grip variations, revolutions, and release points.', 'https://www.iplt20.com/teams/kolkata-knight-riders'),
  ('player_staff', 'specialist_tutelage', 'Sunil Narine', 'carl-crowe', 95, true, 'Crowe remodelled Narine''s bowling action and remains his personal bowling coach.', 'https://www.espncricinfo.com/'),
  ('player_staff', 'specialist_tutelage', 'Matheesha Pathirana', 'dwayne-bravo', 92, true, 'Bravo closely coached Pathirana in the art of the slower ball, dipping yorker, and death bowling craft.', 'https://www.iplt20.com/teams/chennai-super-kings'),
  ('player_staff', 'specialist_tutelage', 'Tushar Deshpande', 'dwayne-bravo', 85, true, 'Bravo coached Deshpande through death-over mechanics during CSK title campaigns.', 'https://www.iplt20.com/teams/chennai-super-kings'),
  ('player_staff', 'specialist_tutelage', 'Mukesh Choudhary', 'eric-simons', 82, true, 'Simons mentored Choudhary''s swing bowling craft and wrist position at CSK.', 'https://www.iplt20.com/teams/chennai-super-kings'),
  ('player_staff', 'specialist_tutelage', 'Ravi Bishnoi', 'anil-kumble', 91, true, 'Kumble scouted Bishnoi and personally coached his unique googly trajectory and fast-arm action.', 'https://www.punjabkingsipl.in/'),
  ('player_staff', 'specialist_tutelage', 'Arshdeep Singh', 'bharat-arun', 84, true, 'Arun worked with Arshdeep on yorker angles and seam presentation in national camps.', 'https://www.bcci.tv/'),
  ('player_staff', 'specialist_tutelage', 'Kuldeep Yadav', 'sairaj-bahutule', 83, true, 'Bahutule worked with Kuldeep on release speed and flight mechanics.', 'https://www.bcci.tv/'),
  ('player_staff', 'specialist_tutelage', 'Harshit Rana', 'bharat-arun', 88, true, 'Arun shaped Harshit Rana''s bowling trajectory, bouncers and slower-ball variations at KKR.', 'https://www.iplt20.com/teams/kolkata-knight-riders'),
  ('player_staff', 'specialist_tutelage', 'Vaibhav Arora', 'bharat-arun', 83, true, 'Arun developed Arora''s two-way swing movement with the new ball at KKR.', 'https://www.iplt20.com/teams/kolkata-knight-riders'),
  ('player_staff', 'specialist_tutelage', 'Mohsin Khan', 'morne-morkel', 86, true, 'Morkel coached Mohsin Khan''s tall release and back-of-a-length bounce at LSG.', 'https://www.lucknowsupergiants.in/'),
  ('player_staff', 'specialist_tutelage', 'Mayank Yadav', 'morne-morkel', 87, true, 'Morkel worked with the express pacer on runup rhythm and explosive seam release at LSG.', 'https://www.lucknowsupergiants.in/'),
  ('player_staff', 'specialist_tutelage', 'Yashasvi Jaiswal', 'vikram-rathour', 89, true, 'Rathour coached Jaiswal''s Test and T20 batting transitions for India and at RR.', 'https://www.rajasthanroyals.com/'),
  ('player_staff', 'specialist_tutelage', 'Shubman Gill', 'vikram-rathour', 88, true, 'Rathour worked on Gill''s weight transfer and back-foot defence across national squads.', 'https://www.bcci.tv/'),
  ('player_staff', 'specialist_tutelage', 'Dhruv Jurel', 'vikram-rathour', 84, true, 'Rathour guided Jurel through his sensational India Test debut and batting development at RR.', 'https://www.rajasthanroyals.com/'),
  ('player_staff', 'specialist_tutelage', 'Rajat Patidar', 'dinesh-karthik', 83, true, 'Karthik mentors Patidar on high-pressure tactical approach and spin execution at RCB.', 'https://www.royalchallengers.com/'),
  ('player_staff', 'specialist_tutelage', 'Ruturaj Gaikwad', 'michael-hussey', 91, true, 'Hussey worked extensively with Gaikwad on tempo building and opening craft at CSK.', 'https://www.iplt20.com/teams/chennai-super-kings'),
  ('player_staff', 'specialist_tutelage', 'Devon Conway', 'michael-hussey', 86, true, 'Hussey and Conway share detailed tactical preparation on subcontinental pitches at CSK.', 'https://www.iplt20.com/teams/chennai-super-kings'),
  ('player_staff', 'talent_champion', 'Rohit Sharma', 'ricky-ponting', 92, true, 'Ponting famously handed over Mumbai Indians captaincy to Rohit in 2013, launching MI''s golden era.', 'https://www.mumbaiindians.com/'),
  ('player_staff', 'talent_champion', 'Rinku Singh', 'abhishek-nayar', 95, true, 'Nayar transformed Rinku''s career at the KKR Academy, backing him through years of injuries.', 'https://www.iplt20.com/teams/kolkata-knight-riders'),
  ('player_staff', 'talent_champion', 'Varun Chakravarthy', 'abhishek-nayar', 88, true, 'Nayar advocated heavily for Chakravarthy''s KKR recruitment and tactical role.', 'https://www.iplt20.com/teams/kolkata-knight-riders'),
  ('player_staff', 'talent_champion', 'Angkrish Raghuvanshi', 'abhishek-nayar', 91, true, 'Nayar has personally coached and championed Raghuvanshi from childhood in Mumbai.', 'https://www.iplt20.com/teams/kolkata-knight-riders'),
  ('player_staff', 'talent_champion', 'Sanju Samson', 'rahul-dravid', 94, true, 'Dravid scouted Samson at Rajasthan Royals trials in 2013 and gave him his IPL debut.', 'https://www.rajasthanroyals.com/'),
  ('player_staff', 'talent_champion', 'Karun Nair', 'rahul-dravid', 88, true, 'Dravid championed Nair across Rajasthan Royals and India A setups.', 'https://www.bcci.tv/'),
  ('player_staff', 'talent_champion', 'Rishabh Pant', 'rahul-dravid', 89, true, 'Dravid developed and backed Pant through the 2016 U19 World Cup and Delhi Daredevils.', 'https://www.bcci.tv/'),
  ('player_staff', 'talent_champion', 'Ishan Kishan', 'rahul-dravid', 87, true, 'Dravid captained Kishan''s development as India U19 head coach in 2016.', 'https://www.bcci.tv/'),
  ('player_staff', 'talent_champion', 'Washington Sundar', 'rahul-dravid', 85, true, 'Dravid nurtured Sundar''s early career in the India pathway system.', 'https://www.bcci.tv/'),
  ('player_staff', 'talent_champion', 'Ayush Badoni', 'gautam-gambhir', 90, true, 'Gambhir scouted Badoni, backed him at the auction and gave him immediate finishing responsibility at LSG.', 'https://www.lucknowsupergiants.in/'),
  ('player_staff', 'talent_champion', 'Mayank Yadav', 'gautam-gambhir', 88, true, 'Gambhir scouted the raw pace sensation and brought him to Lucknow Super Giants.', 'https://www.lucknowsupergiants.in/'),
  ('player_staff', 'talent_champion', 'Harshit Rana', 'gautam-gambhir', 92, true, 'Gambhir backed Harshit''s fiery temperament and promoted him to frontline death bowler at KKR and India.', 'https://www.iplt20.com/teams/kolkata-knight-riders'),
  ('player_staff', 'former_teammates', 'Rohit Sharma', 'kieron-pollard', 93, true, 'Legendary teammates who won five IPL titles together before Pollard transitioned to batting coach.', 'https://www.mumbaiindians.com/'),
  ('player_staff', 'former_teammates', 'Jasprit Bumrah', 'kieron-pollard', 88, true, 'Longtime Mumbai Indians teammates across multiple trophy-winning campaigns.', 'https://www.mumbaiindians.com/'),
  ('player_staff', 'former_teammates', 'Suryakumar Yadav', 'kieron-pollard', 86, true, 'Shared the Mumbai Indians middle order during championship-winning seasons.', 'https://www.mumbaiindians.com/'),
  ('player_staff', 'former_teammates', 'Hardik Pandya', 'kieron-pollard', 91, true, 'Famous finishing brothers-in-arms for Mumbai Indians over numerous seasons.', 'https://www.mumbaiindians.com/'),
  ('player_staff', 'former_teammates', 'MS Dhoni', 'dwayne-bravo', 96, true, 'Dhoni and Bravo shared over a decade of CSK brotherhood before Bravo joined the coaching staff.', 'https://www.iplt20.com/teams/chennai-super-kings'),
  ('player_staff', 'former_teammates', 'Ravindra Jadeja', 'dwayne-bravo', 92, true, 'CSK''s legendary all-round engine room for multiple title-winning campaigns.', 'https://www.iplt20.com/teams/chennai-super-kings'),
  ('player_staff', 'former_teammates', 'Ruturaj Gaikwad', 'michael-hussey', 78, true, 'Teammates in CSK squad before Hussey focused full-time on coaching Gaikwad.', 'https://www.iplt20.com/teams/chennai-super-kings'),
  ('player_staff', 'former_teammates', 'Virat Kohli', 'dinesh-karthik', 92, true, 'Longtime India and RCB teammates before Karthik became RCB''s batting coach.', 'https://www.royalchallengers.com/'),
  ('player_staff', 'former_teammates', 'Mohammed Siraj', 'dinesh-karthik', 84, true, 'Played together for multiple seasons at Royal Challengers Bengaluru.', 'https://www.royalchallengers.com/'),
  ('player_staff', 'former_teammates', 'Shubman Gill', 'matthew-wade', 83, true, 'Gujarat Titans teammates in the 2022 title-winning squad.', 'https://www.gujarattitansipl.com/'),
  ('player_staff', 'former_teammates', 'Rashid Khan', 'matthew-wade', 82, true, 'Shared the Gujarat Titans dugout during their championship run.', 'https://www.gujarattitansipl.com/'),
  ('staff_staff', 'trusted_colleague', 'dwayne-bravo', 'andre-russell', 88, true, 'West Indies T20 World Cup champions and close Caribbean coaching compatriots.', 'https://www.windiescricket.com/'),
  ('player_staff', 'former_teammates', 'Sunil Narine', 'dwayne-bravo', 87, true, 'Longtime West Indies international teammates and Caribbean premier league competitors.', 'https://www.windiescricket.com/'),
  ('player_staff', 'former_teammates', 'Nicholas Pooran', 'kieron-pollard', 89, true, 'Pooran succeeded Pollard as West Indies white-ball captain and shares close mentorship.', 'https://www.windiescricket.com/'),
  ('player_staff', 'former_teammates', 'Shimron Hetmyer', 'kieron-pollard', 83, true, 'West Indies international middle-order teammates.', 'https://www.windiescricket.com/'),
  ('player_staff', 'coached', 'Rohit Sharma', 'gautam-gambhir', 88, true, 'Gambhir took over as India head coach with Rohit as his senior captain.', 'https://www.bcci.tv/'),
  ('player_staff', 'coached', 'Virat Kohli', 'gautam-gambhir', 86, true, 'Longstanding Delhi cricket connection and senior player under Gambhir''s India coaching tenure.', 'https://www.bcci.tv/'),
  ('player_staff', 'coached', 'Rohit Sharma', 'rahul-dravid', 94, true, 'Captain and coach partnership that reached the 2023 ODI World Cup final and won the 2024 T20 World Cup.', 'https://www.bcci.tv/'),
  ('player_staff', 'coached', 'Virat Kohli', 'rahul-dravid', 90, true, 'Shared leadership during Dravid''s India head coach era.', 'https://www.bcci.tv/'),
  ('player_staff', 'coached', 'Travis Head', 'daniel-vettori', 87, true, 'Vettori coached Head''s devastating attacking game at Sunrisers Hyderabad.', 'https://www.sunrisershyderabad.in/'),
  ('player_staff', 'coached', 'Heinrich Klaasen', 'daniel-vettori', 86, true, 'Vettori''s SRH tactical setup gave Klaasen complete freedom against spin.', 'https://www.sunrisershyderabad.in/'),
  ('player_staff', 'coached', 'Prithvi Shaw', 'ricky-ponting', 84, true, 'Ponting passionately worked with Shaw on batting trigger movements and off-field discipline at DC.', 'https://www.delhicapitals.in/'),
  ('player_staff', 'coached', 'Arshdeep Singh', 'ricky-ponting', 82, true, 'Ponting leads Punjab Kings with Arshdeep as his frontline pace attack spearhead.', 'https://www.punjabkingsipl.in/'),
  ('player_staff', 'coached', 'Sam Curran', 'trevor-bayliss', 85, true, 'Bayliss coached Curran across England national duties and Punjab Kings.', 'https://www.ecb.co.uk/'),
  ('player_staff', 'coached', 'Liam Livingstone', 'trevor-bayliss', 82, true, 'Bayliss entrusted Livingstone with key middle-order batting duties at PBKS.', 'https://www.punjabkingsipl.in/'),
  ('player_staff', 'coached', 'Jos Buttler', 'trevor-bayliss', 90, true, 'Bayliss built England''s transformative white-ball batting philosophy around Buttler.', 'https://www.ecb.co.uk/'),
  ('player_staff', 'coached', 'Harry Brook', 'brendon-mccullum', 92, true, 'McCullum shaped Brook''s ultra-fearless batting style across England setups.', 'https://www.ecb.co.uk/'),
  ('player_staff', 'coached', 'Phil Salt', 'brendon-mccullum', 85, true, 'McCullum backs Salt''s attacking aggression as England white-ball coach.', 'https://www.ecb.co.uk/'),
  ('staff_staff', 'inner_circle_assistant', 'trevor-bayliss', 'paul-farbrace', 100, true, 'Bayliss personally recruited Farbrace as his assistant for Sri Lanka and reunited with him in the same structure for England.', 'https://www.bbc.co.uk/sport/cricket/41917102'),
  ('staff_staff', 'inner_circle_assistant', 'ricky-ponting', 'james-hopes', 96, true, 'Hopes worked under Ponting at Delhi and declined a Delhi extension to continue alongside him at Punjab.', 'https://www.cricbuzz.com/cricket-news/132208/pbks-retain-brad-haddin-and-sunil-joshi-james-hopes-may-join-support-staff-cricbuzzcom'),
  ('staff_staff', 'inner_circle_assistant', 'rahul-dravid', 'vikram-rathour', 95, true, 'After their successful India partnership, Rathour explicitly reunited with Dravid at Rajasthan and described their strong rapport.', 'https://www.espn.com/cricket/story/_/id/41338406/ipl-vikram-rathour-joins-rajasthan-royals-batting-coach'),
  ('staff_staff', 'inner_circle_assistant', 'gautam-gambhir', 'ryan-ten-doeschate', 94, true, 'Ten Doeschate moved from Gambhir''s KKR group into his India support staff.', 'https://www.aajtak.in/sports/cricket/story/gautam-gambhir-coaching-staff-is-inexperienced-ryan-ten-doeschate-abhishek-nayar-not-play-test-cricket-team-india-tspo-dskc-2087793-2024-11-04'),
  ('staff_staff', 'inner_circle_assistant', 'gautam-gambhir', 'morne-morkel', 93, true, 'Morkel worked in Gambhir-led structures at Lucknow before being recommended by Gambhir as bowling coach for his India staff.', 'https://www.espn.in/cricket/story/_/id/40856135/morne-morkel-appointed-india-bowling-coach'),
  ('staff_staff', 'inner_circle_assistant', 'mickey-arthur', 'grant-flower', 92, true, 'Flower served in Arthur''s Pakistan staff and subsequently joined the Sri Lanka coaching structure led by Arthur.', 'https://tribune.com.pk/story/1099949/arthurs-roots-to-grow-wings-to-fly-mantra-for-pakistan'),
  ('staff_staff', 'trusted_colleague', 'stephen-fleming', 'eric-simons', 90, true, 'Simons has served for years in Fleming-led Chennai and Joburg Super Kings structures.', 'https://www.wisden.com/cricket-news/sa20-2024-coaches-full-list-support-staff-each-sa20-team'),
  ('staff_staff', 'trusted_colleague', 'tom-moody', 'simon-helmot', 90, true, 'Helmot was Moody''s long-serving assistant through the original Sunrisers cycle and their later return.', 'https://www.espn.com/cricket/story/_/id/34508567/ipl-2023-srh-brian-lara-takes-tom-moody-sunrisers-head-coach'),
  ('staff_staff', 'trusted_colleague', 'stephen-fleming', 'michael-hussey', 87, true, 'Hussey has remained a central batting coach throughout Fleming''s long-running Chennai staff.', 'https://www.iplt20.com/teams/chennai-super-kings'),
  ('staff_staff', 'trusted_colleague', 'rahul-dravid', 'paras-mhambrey', 86, true, 'Mhambrey worked in Dravid-led India pathway and senior national-team structures across multiple cycles.', 'https://www.bcci.tv/articles/2021/news/155451/rahul-dravid-appointed-head-coach-of-team-india-men-s-senior-national-team'),
  ('staff_staff', 'trusted_colleague', 'mahela-jayawardene', 'lasith-malinga', 85, true, 'Malinga served as a Mumbai bowling mentor under Jayawardene in 2018 and returned to his later Mumbai coaching group.', 'https://www.mumbaiindians.com/news/welcome-back-head-coach-mahela-jayawardene-ipl-2025'),
  ('staff_staff', 'trusted_colleague', 'ricky-ponting', 'pravin-amre', 83, true, 'Amre was a long-serving senior member of Ponting''s Delhi Capitals coaching group.', 'https://www.espn.com/cricket/story/_/id/40553669/ricky-ponting-delhi-capitals-part-ways'),
  ('staff_staff', 'trusted_colleague', 'tom-moody', 'muttiah-muralitharan', 82, true, 'Muralitharan was the specialist constant across Moody''s long Sunrisers coaching tenure.', 'https://www.iplt20.com/teams/sunrisers-hyderabad'),
  ('staff_staff', 'trusted_colleague', 'mahela-jayawardene', 'kieron-pollard', 81, true, 'Pollard was a senior leader throughout Jayawardene''s title-winning Mumbai tenure and later joined the franchise coaching staff.', 'https://www.mumbaiindians.com/news/welcome-back-head-coach-mahela-jayawardene-ipl-2025'),
  ('staff_staff', 'trusted_colleague', 'ricky-ponting', 'brad-haddin', 78, true, 'Haddin forms part of Ponting''s senior Punjab support group after their overlapping Australia coaching work.', 'https://www.espn.in/cricket/story/_/id/44385100/ipl-2025-brad-haddin-backs-ricky-ponting-view-build-greatest-punjab-kings-team'),
  ('staff_staff', 'trusted_colleague', 'rahul-dravid', 't-dilip', 76, true, 'Dilip served throughout Dravid''s senior India head-coach cycle, including the 2024 T20 World Cup success.', 'https://www.bcci.tv/articles/2021/news/155451/rahul-dravid-appointed-head-coach-of-team-india-men-s-senior-national-team'),
  ('staff_staff', 'trusted_colleague', 'mickey-arthur', 'morne-morkel', 75, true, 'Arthur selected Morkel for the Pakistan structure he assembled as team director.', 'https://www.wisden.com/cricket-interviews/cricket-interviews/mickey-arthur-i-continually-witness-pakistan-cricket-nailing-it-in-the-foot'),
  ('staff_staff', 'trusted_colleague', 'kumar-sangakkara', 'trevor-penney', 74, true, 'Penney has served in Rajasthan''s senior coaching group during Sangakkara''s extended cricket-leadership tenure.', 'https://www.rajasthanroyals.com/latest-news/kumar-sangakkara-rr-new-head-coach-ipl-2026'),
  ('staff_staff', 'trusted_colleague', 'justin-langer', 'brad-haddin', 72, true, 'Haddin served as Australia''s fielding coach during the opening period of Langer''s national-team tenure.', 'https://www.cricket.com.au/news/3303872/mcdonald-secures-australia-assistant-coach-role'),
  ('staff_staff', 'trusted_colleague', 'brendon-mccullum', 'marcus-trescothick', 80, true, 'England senior coaching overlap.', 'https://www.ecb.co.uk/news/4106595/ecb-announces-brendon-mccullum-as-england-mens-whiteball-head-coach'),
  ('staff_staff', 'trusted_colleague', 'ashish-nehra', 'parthiv-patel', 76, true, 'Gujarat Titans head coach and assistant coach partnership.', 'https://www.gujarattitansipl.com/news/parthiv-patel-joins-gujarat-titans-as-assistant-coach-for-tata-ipl-2025'),
  ('staff_staff', 'trusted_colleague', 'ravi-shastri', 'bharat-arun', 88, true, 'Long India head coach and bowling coach partnership.', 'https://www.bcci.tv/news/article/the-boys-have-become-men-ravi-shastri'),
  ('staff_staff', 'trusted_colleague', 'andy-flower', 'dinesh-karthik', 80, true, 'Bengaluru head coach and batting coach partnership.', 'https://www.royalchallengers.com/rcb-cricket-news/news/ive-really-enjoyed-watching-andy-mo-bobat-on-the-dressing-room-atmosphere'),
  ('staff_staff', 'trusted_colleague', 'gautam-gambhir', 'abhishek-nayar', 95, true, 'Architects of KKR''s 2024 championship who joined forces again in the Indian national coaching setup.', 'https://www.bcci.tv/'),
  ('staff_staff', 'trusted_colleague', 'daniel-vettori', 'james-franklin', 85, true, 'Vettori and Franklin work closely as head coach and bowling coach at Sunrisers Hyderabad.', 'https://www.sunrisershyderabad.in/'),
  ('staff_staff', 'trusted_colleague', 'daniel-vettori', 'muttiah-muralitharan', 87, true, 'Vettori and Muralitharan direct Sunrisers Hyderabad''s tactical bowling plans.', 'https://www.sunrisershyderabad.in/'),
  ('staff_staff', 'trusted_colleague', 'chandrakant-pandit', 'bharat-arun', 88, true, 'Head coach and bowling coach partnership that delivered the 2024 IPL title for KKR.', 'https://www.iplt20.com/teams/kolkata-knight-riders'),
  ('staff_staff', 'trusted_colleague', 'chandrakant-pandit', 'abhishek-nayar', 86, true, 'Pandit and Nayar formed the Indian domestic coaching brain trust at Kolkata Knight Riders.', 'https://www.iplt20.com/teams/kolkata-knight-riders'),
  ('staff_staff', 'trusted_colleague', 'justin-langer', 'lance-klusener', 84, true, 'Langer and Klusener formed the head coach and assistant coach setup at Lucknow Super Giants.', 'https://www.lucknowsupergiants.in/'),
  ('staff_staff', 'trusted_colleague', 'stephen-fleming', 'dwayne-bravo', 92, true, 'Fleming brought Bravo directly onto his CSK coaching staff upon Bravo''s IPL retirement.', 'https://www.iplt20.com/teams/chennai-super-kings'),
  ('staff_staff', 'trusted_colleague', 'ashish-nehra', 'aashish-kapoor', 82, true, 'Foundational members of Gujarat Titans'' inaugural coaching and scouting staff.', 'https://www.gujarattitansipl.com/'),
  ('staff_staff', 'trusted_colleague', 'ashish-nehra', 'naeem-amin', 84, true, 'Longstanding tactical and fielding collaboration within Gujarat Titans dugout.', 'https://www.gujarattitansipl.com/'),
  ('staff_staff', 'trusted_colleague', 'ashish-nehra', 'narender-negi', 82, true, 'Part of Gujarat Titans'' trusted core backroom team.', 'https://www.gujarattitansipl.com/'),
  ('staff_staff', 'trusted_colleague', 'mahela-jayawardene', 'shane-bond', 90, true, 'Head coach and bowling coach partnership across multiple Mumbai Indians championship seasons.', 'https://www.mumbaiindians.com/'),
  ('staff_staff', 'trusted_colleague', 'mahela-jayawardene', 'kumar-sangakkara', 96, true, 'Legendary Sri Lankan leadership duo who co-captained and shaped modern Sri Lankan cricket.', 'https://www.srilankacricket.lk/'),
  ('staff_staff', 'trusted_colleague', 'rahul-dravid', 'kumar-sangakkara', 88, true, 'Senior cricket leadership peers who collaborated closely on Rajasthan Royals'' strategic blueprint.', 'https://www.rajasthanroyals.com/'),
  ('staff_staff', 'trusted_colleague', 'gautam-gambhir', 'sitanshu-kotak', 85, true, 'Kotak serves as key batting support and India A bridge in Gambhir''s national coaching regime.', 'https://www.bcci.tv/'),
  ('staff_staff', 'trusted_colleague', 'andy-flower', 'richard-halsall', 88, true, 'Halsall was Flower''s trusted fielding coach during England''s world number one era.', 'https://www.ecb.co.uk/'),
  ('staff_staff', 'trusted_colleague', 'ricky-ponting', 'sairaj-bahutule', 80, true, 'Ponting brought Bahutule into Punjab Kings as his lead spin bowling coach.', 'https://www.punjabkingsipl.in/'),
  ('staff_staff', 'trusted_colleague', 'ricky-ponting', 'matthew-wade', 83, true, 'Ponting selected Wade as assistant/wicketkeeping coach in his new Punjab Kings structure.', 'https://www.punjabkingsipl.in/'),
  ('staff_staff', 'trusted_colleague', 'sourav-ganguly', 'ricky-ponting', 91, true, 'Director of Cricket and Head Coach brain trust at Delhi Capitals across five seasons.', 'https://www.delhicapitals.in/'),
  ('staff_staff', 'trusted_colleague', 'sourav-ganguly', 'pravin-amre', 85, true, 'Delhi Capitals cricket operations and batting leadership colleagues.', 'https://www.delhicapitals.in/'),
  ('player_staff', 'idol', 'Jasprit Bumrah', 'lasith-malinga', 92, false, 'Mumbai Indians records Malinga as one of Bumrah''s early idols.', 'https://www.mumbaiindians.com/amp/news/jasprit-bumrah-blue-blood-death-bowling'),
  ('player_staff', 'idol', 'Jasprit Bumrah', 'zaheer-khan', 84, false, 'Mumbai Indians records Zaheer as one of Bumrah''s early idols.', 'https://www.mumbaiindians.com/amp/news/jasprit-bumrah-blue-blood-death-bowling'),
  ('player_staff', 'idol', 'Ruturaj Gaikwad', 'ms-dhoni', 95, false, 'Gaikwad has frequently named MS Dhoni as his cricket hero and calm leadership model.', 'https://www.iplt20.com/news/article/ruturaj-gaikwad-takes-over-chennai-super-kings-captaincy-from-ms-dhoni'),
  ('player_player', 'idol', 'Yashasvi Jaiswal', 'Virat Kohli', 94, false, 'Jaiswal publicly stated Kohli is his ultimate batting idol and fitness benchmark.', 'https://www.bcci.tv/'),
  ('player_player', 'idol', 'Shubman Gill', 'Virat Kohli', 93, false, 'Gill has idolized Kohli since childhood, wearing #77 and modelling his intensity on him.', 'https://www.bcci.tv/'),
  ('player_staff', 'idol', 'Rinku Singh', 'suresh-raina', 92, false, 'Rinku idolises UP legend Suresh Raina as his batting and fielding role model.', 'https://www.bcci.tv/'),
  ('player_player', 'idol', 'Riyan Parag', 'Virat Kohli', 93, false, 'Parag has consistently described Kohli as his idol and batting inspiration.', 'https://www.rajasthanroyals.com/'),
  ('player_staff', 'idol', 'Tilak Varma', 'suresh-raina', 90, false, 'Tilak grew up idolising fellow left-hander and middle-order stalwart Suresh Raina.', 'https://www.mumbaiindians.com/'),
  ('player_player', 'idol', 'Nitish Kumar Reddy', 'Virat Kohli', 91, false, 'Nitish Reddy has named Kohli as his idol for game awareness and fitness.', 'https://www.sunrisershyderabad.in/'),
  ('player_staff', 'idol', 'Rohit Sharma', 'sachin-tendulkar', 96, false, 'Rohit grew up worshiping Sachin Tendulkar before playing alongside him for Mumbai and India.', 'https://www.mumbaiindians.com/'),
  ('player_staff', 'idol', 'Virat Kohli', 'sachin-tendulkar', 98, false, 'Kohli famously stated Tendulkar was the sole reason he picked up a cricket bat.', 'https://www.bcci.tv/'),
  ('player_staff', 'idol', 'Sanju Samson', 'rahul-dravid', 92, false, 'Samson has frequently hailed Rahul Dravid as his lifelong idol and guiding light.', 'https://www.rajasthanroyals.com/'),
  ('player_staff', 'idol', 'Dhruv Jurel', 'ms-dhoni', 93, false, 'Jurel considers MS Dhoni his wicketkeeping and finishing idol.', 'https://www.rajasthanroyals.com/'),
  ('player_staff', 'idol', 'Ishan Kishan', 'ms-dhoni', 92, false, 'Hailing from Jharkhand, Kishan grew up modeling his wicketkeeping on MS Dhoni.', 'https://www.mumbaiindians.com/'),
  ('player_staff', 'idol', 'Rishabh Pant', 'ms-dhoni', 94, false, 'Pant shares a deep bond with Dhoni, looking up to him as his elder brother and hero.', 'https://www.bcci.tv/'),
  ('player_staff', 'idol', 'Mayank Yadav', 'dale-steyn', 94, false, 'Mayank Yadav grew up watching Dale Steyn videos and modeled his fast bowling after him.', 'https://www.lucknowsupergiants.in/');

do $$
declare
  bad text;
begin
  if (select count(*) from _person_dynamics_seed) <> 248 then
    raise exception 'Expected 248 person dynamics seeds';
  end if;

  select format('%s / %s / %s (matches: %s, %s)', category, person1_key, person2_key, first_matches, second_matches)
  into bad
  from (
    select s.*,
      case when s.category in ('player_player', 'player_staff')
        then (select count(*) from public.players p where p.name = s.person1_key)
        else (select count(*) from public.staff_members m where m.slug = s.person1_key) end as first_matches,
      case when s.category = 'player_player'
        then (select count(*) from public.players p where p.name = s.person2_key)
        else (select count(*) from public.staff_members m where m.slug = s.person2_key) end as second_matches
    from _person_dynamics_seed s
  ) resolved
  where first_matches <> 1 or second_matches <> 1
  limit 1;
  if bad is not null then
    raise exception 'Missing or ambiguous person dynamics participant: %', bad;
  end if;

  select s.dynamic_type into bad
  from _person_dynamics_seed s
  left join public.dynamic_types t on t.id = s.dynamic_type
  where t.id is null or (t.category <> s.category and t.category <> 'universal')
  limit 1;
  if bad is not null then
    raise exception 'Missing or incompatible dynamic type: %', bad;
  end if;
end $$;

insert into public.person_dynamics (
  relationship_category, dynamic_type, rating, is_bidirectional,
  person_1_type, person_1_player_id, person_1_staff_id, person_1_name, person_1_role_label, person_1_reason,
  person_2_type, person_2_player_id, person_2_staff_id, person_2_name, person_2_role_label, person_2_reason,
  story, evidence_url, is_active
)
select
  s.category, s.dynamic_type, s.rating, s.is_bidirectional,
  case when s.category = 'staff_staff' then 'staff' else 'player' end,
  case when s.category <> 'staff_staff' then (select p.id from public.players p where p.name = s.person1_key) end,
  case when s.category = 'staff_staff' then (select m.id from public.staff_members m where m.slug = s.person1_key) end,
  case when s.category = 'staff_staff' then (select m.full_name from public.staff_members m where m.slug = s.person1_key) else s.person1_key end,
  case when s.dynamic_type = 'idol' then 'Admirer' when s.category = 'staff_staff' then 'Coach' else 'Player' end,
  s.reason,
  case when s.category = 'player_player' then 'player' else 'staff' end,
  case when s.category = 'player_player' then (select p.id from public.players p where p.name = s.person2_key) end,
  case when s.category <> 'player_player' then (select m.id from public.staff_members m where m.slug = s.person2_key) end,
  case when s.category = 'player_player' then s.person2_key else (select m.full_name from public.staff_members m where m.slug = s.person2_key) end,
  case when s.dynamic_type = 'idol' then 'Idol' when s.category = 'player_player' then 'Player' else 'Coach' end,
  s.reason,
  s.reason, s.evidence_url, true
from _person_dynamics_seed s
on conflict do nothing;

drop table _person_dynamics_seed;
