-- Additional real-world coaches for 2026 starts. Ratings are game estimates.
-- Source URLs and detailed rating rationale live in lib/data/staffDirectoryAdditions.ts.

INSERT INTO public.staff_members (id, slug, full_name, known_as, date_of_birth, country, biography, primary_role, secondary_roles, current_real_team_id, real_contract_end_year, reputation, current_ability, potential_ability, experience_years, salary_expectation, compensation_cost, ambition, loyalty, adaptability, learning_rate, development_phase, retirement_age, personality, coaching_philosophy, preferred_team_strategy, is_available, is_generated, is_active, batting_coaching, pace_bowling_coaching, spin_bowling_coaching, fielding_coaching, wicketkeeping_coaching, technical_coaching, tactical_knowledge, player_development, youth_development, judging_ability, judging_potential, man_management, motivation, profile_confidence, rating_basis)
VALUES ('e0260000-0000-4000-8000-000000000001', 'monty-desai', 'Monty Desai', 'Monty Desai', NULL, 'India', 'Former Nepal and Canada national head coach, recognised for developing associate-nation batting groups and building cohesive teams. Left the Canada post in August 2026.', 'head_coach', ARRAY['batting_coach', 'assistant_coach']::text[], NULL, NULL, 75, 78, 80, 20, 12500000, 0, 76, 67, 88, 70, 'peak', 68, 'supportive', 'development', 'Adaptive', TRUE, FALSE, TRUE, 16, 7, 9, 11, 7, 16, 17, 18, 18, 16, 18, 18, 18, 'medium', 'Nepal''s ODI revival and World Cup qualification support strong development, tactical and man-management ratings; Canada tenure ended in August 2026.')
ON CONFLICT DO NOTHING;

INSERT INTO public.staff_traits (staff_id, youth_developer, academy_builder, senior_developer, player_favourite, youngster_preference, high_potential_preference, tactical_aggression, data_reliance)
VALUES ('e0260000-0000-4000-8000-000000000001', TRUE, TRUE, TRUE, TRUE, 82, 84, 57, 62)
ON CONFLICT DO NOTHING;

INSERT INTO public.staff_members (id, slug, full_name, known_as, date_of_birth, country, biography, primary_role, secondary_roles, current_real_team_id, real_contract_end_year, reputation, current_ability, potential_ability, experience_years, salary_expectation, compensation_cost, ambition, loyalty, adaptability, learning_rate, development_phase, retirement_age, personality, coaching_philosophy, preferred_team_strategy, is_available, is_generated, is_active, batting_coaching, pace_bowling_coaching, spin_bowling_coaching, fielding_coaching, wicketkeeping_coaching, technical_coaching, tactical_knowledge, player_development, youth_development, judging_ability, judging_potential, man_management, motivation, profile_confidence, rating_basis)
VALUES ('e0260000-0000-4000-8000-000000000002', 'shaun-tait', 'Shaun Tait', 'Shaun Tait', '1983-02-22', 'Australia', 'Former Australia fast bowler and Bangladesh pace bowling coach. Resigned from Bangladesh in June 2026.', 'pace_bowling_coach', ARRAY['coach', 'assistant_coach']::text[], NULL, NULL, 78, 79, 82, 8, 13500000, 0, 80, 68, 78, 76, 'peak', 65, 'driven', 'aggressive', 'Aggressive', TRUE, FALSE, TRUE, 5, 19, 4, 9, 3, 17, 14, 17, 15, 16, 16, 15, 17, 'medium', 'Specialist pace coaching and Bangladesh''s improved pace unit support a high pace rating; head-coach skills remain more modest.')
ON CONFLICT DO NOTHING;

INSERT INTO public.staff_traits (staff_id, pace_specialist, death_overs_specialist, aggressive_identity, tactical_aggression, data_reliance, youngster_preference)
VALUES ('e0260000-0000-4000-8000-000000000002', TRUE, TRUE, TRUE, 79, 52, 69)
ON CONFLICT DO NOTHING;

INSERT INTO public.staff_members (id, slug, full_name, known_as, date_of_birth, country, biography, primary_role, secondary_roles, current_real_team_id, real_contract_end_year, reputation, current_ability, potential_ability, experience_years, salary_expectation, compensation_cost, ambition, loyalty, adaptability, learning_rate, development_phase, retirement_age, personality, coaching_philosophy, preferred_team_strategy, is_available, is_generated, is_active, batting_coaching, pace_bowling_coaching, spin_bowling_coaching, fielding_coaching, wicketkeeping_coaching, technical_coaching, tactical_knowledge, player_development, youth_development, judging_ability, judging_potential, man_management, motivation, profile_confidence, rating_basis)
VALUES ('e0260000-0000-4000-8000-000000000003', 'luke-ronchi', 'Luke Ronchi', 'Luke Ronchi', '1981-04-23', 'New Zealand', 'Former New Zealand batting coach, appointed Melbourne Renegades head coach in July 2026. Brings batting and wicketkeeping expertise.', 'batting_coach', ARRAY['wicketkeeping_coach', 'head_coach']::text[], NULL, NULL, 79, 80, 83, 7, 14500000, 0, 83, 74, 82, 79, 'peak', 67, 'supportive', 'attacking', 'Aggressive', TRUE, FALSE, TRUE, 18, 5, 6, 14, 18, 17, 16, 17, 15, 16, 16, 17, 17, 'medium', 'Long New Zealand batting-coach tenure and wicketkeeping background justify dual specialism; new BBL head role raises leadership potential.')
ON CONFLICT DO NOTHING;

INSERT INTO public.staff_traits (staff_id, batting_specialist, wicketkeeping_specialist, player_favourite, powerplay_specialist, tactical_aggression, youngster_preference, data_reliance)
VALUES ('e0260000-0000-4000-8000-000000000003', TRUE, TRUE, TRUE, TRUE, 74, 71, 58)
ON CONFLICT DO NOTHING;

INSERT INTO public.staff_members (id, slug, full_name, known_as, date_of_birth, country, biography, primary_role, secondary_roles, current_real_team_id, real_contract_end_year, reputation, current_ability, potential_ability, experience_years, salary_expectation, compensation_cost, ambition, loyalty, adaptability, learning_rate, development_phase, retirement_age, personality, coaching_philosophy, preferred_team_strategy, is_available, is_generated, is_active, batting_coaching, pace_bowling_coaching, spin_bowling_coaching, fielding_coaching, wicketkeeping_coaching, technical_coaching, tactical_knowledge, player_development, youth_development, judging_ability, judging_potential, man_management, motivation, profile_confidence, rating_basis)
VALUES ('e0260000-0000-4000-8000-000000000004', 'kevin-pietersen', 'Kevin Pietersen', 'Kevin Pietersen', '1980-06-27', 'England', 'Former England batter, Delhi Capitals mentor in 2025 and specialist mentor to England''s white-ball teams from September 2026.', 'mentor', ARRAY['batting_coach', 'coach']::text[], NULL, NULL, 91, 79, 82, 2, 19000000, 0, 83, 66, 79, 78, 'developing', 67, 'outspoken', 'attacking', 'Aggressive', TRUE, FALSE, TRUE, 18, 3, 5, 11, 3, 16, 15, 15, 13, 16, 15, 15, 18, 'medium', 'Elite batting experience and current England mentoring remit support batting, reputation and motivation; short formal coaching tenure limits other skills.')
ON CONFLICT DO NOTHING;

INSERT INTO public.staff_traits (staff_id, batting_specialist, elite_motivator, aggressive_identity, star_player_preference, tactical_aggression, data_reliance)
VALUES ('e0260000-0000-4000-8000-000000000004', TRUE, TRUE, TRUE, 79, 85, 49)
ON CONFLICT DO NOTHING;

INSERT INTO public.staff_members (id, slug, full_name, known_as, date_of_birth, country, biography, primary_role, secondary_roles, current_real_team_id, real_contract_end_year, reputation, current_ability, potential_ability, experience_years, salary_expectation, compensation_cost, ambition, loyalty, adaptability, learning_rate, development_phase, retirement_age, personality, coaching_philosophy, preferred_team_strategy, is_available, is_generated, is_active, batting_coaching, pace_bowling_coaching, spin_bowling_coaching, fielding_coaching, wicketkeeping_coaching, technical_coaching, tactical_knowledge, player_development, youth_development, judging_ability, judging_potential, man_management, motivation, profile_confidence, rating_basis)
VALUES ('e0260000-0000-4000-8000-000000000005', 'matthew-mott', 'Matthew Mott', 'Matthew Mott', '1973-10-03', 'Australia', 'Former England white-ball and Australia women head coach, appointed Sydney Sixers men''s BBL head coach in July 2026.', 'head_coach', ARRAY['assistant_coach', 'batting_coach']::text[], NULL, NULL, 84, 84, 86, 18, 19500000, 0, 78, 73, 79, 69, 'peak', 69, 'calm', 'balanced', 'Adaptive', TRUE, FALSE, TRUE, 16, 9, 9, 12, 6, 16, 18, 17, 15, 17, 16, 18, 17, 'medium', 'Multiple senior head-coach roles and international trophies support strong tactics and management, with a meaningful but narrower batting specialism.')
ON CONFLICT DO NOTHING;

INSERT INTO public.staff_traits (staff_id, elite_man_manager, big_game_coach, squad_builder, squad_rotation_preference, tactical_aggression, data_reliance)
VALUES ('e0260000-0000-4000-8000-000000000005', TRUE, TRUE, TRUE, 70, 64, 68)
ON CONFLICT DO NOTHING;

INSERT INTO public.staff_members (id, slug, full_name, known_as, date_of_birth, country, biography, primary_role, secondary_roles, current_real_team_id, real_contract_end_year, reputation, current_ability, potential_ability, experience_years, salary_expectation, compensation_cost, ambition, loyalty, adaptability, learning_rate, development_phase, retirement_age, personality, coaching_philosophy, preferred_team_strategy, is_available, is_generated, is_active, batting_coaching, pace_bowling_coaching, spin_bowling_coaching, fielding_coaching, wicketkeeping_coaching, technical_coaching, tactical_knowledge, player_development, youth_development, judging_ability, judging_potential, man_management, motivation, profile_confidence, rating_basis)
VALUES ('e0260000-0000-4000-8000-000000000006', 'darren-lehmann', 'Darren Lehmann', 'Darren Lehmann', '1970-02-05', 'Australia', 'Former Australia men''s head coach and current Northamptonshire head coach, contracted through 2029.', 'head_coach', ARRAY['batting_coach', 'mentor']::text[], NULL, NULL, 85, 83, 84, 22, 18500000, 0, 73, 77, 75, 65, 'peak', 70, 'direct', 'attacking', 'Aggressive', TRUE, FALSE, TRUE, 17, 8, 10, 11, 5, 16, 18, 16, 14, 17, 15, 17, 18, 'medium', 'Long national, franchise and county head-coaching record supports leadership and batting expertise; he is under a current county contract.')
ON CONFLICT DO NOTHING;

INSERT INTO public.staff_traits (staff_id, elite_motivator, big_game_coach, aggressive_identity, veteran_preference, tactical_aggression, data_reliance)
VALUES ('e0260000-0000-4000-8000-000000000006', TRUE, TRUE, TRUE, 69, 79, 55)
ON CONFLICT DO NOTHING;

INSERT INTO public.staff_members (id, slug, full_name, known_as, date_of_birth, country, biography, primary_role, secondary_roles, current_real_team_id, real_contract_end_year, reputation, current_ability, potential_ability, experience_years, salary_expectation, compensation_cost, ambition, loyalty, adaptability, learning_rate, development_phase, retirement_age, personality, coaching_philosophy, preferred_team_strategy, is_available, is_generated, is_active, batting_coaching, pace_bowling_coaching, spin_bowling_coaching, fielding_coaching, wicketkeeping_coaching, technical_coaching, tactical_knowledge, player_development, youth_development, judging_ability, judging_potential, man_management, motivation, profile_confidence, rating_basis)
VALUES ('e0260000-0000-4000-8000-000000000007', 'troy-cooley', 'Troy Cooley', 'Troy Cooley', NULL, 'Australia', 'England men''s elite national pace bowling lead since January 2026, with extensive prior England, Australia and India academy work.', 'pace_bowling_coach', ARRAY['coach', 'assistant_coach']::text[], NULL, NULL, 80, 85, 86, 25, 17000000, 0, 72, 76, 82, 69, 'peak', 70, 'analytical', 'technical', 'Adaptive', TRUE, FALSE, TRUE, 5, 19, 6, 10, 4, 19, 16, 19, 19, 17, 18, 16, 16, 'medium', 'ECB national pace lead and long academy record justify elite pace, technical and youth-development scores.')
ON CONFLICT DO NOTHING;

INSERT INTO public.staff_traits (staff_id, pace_specialist, youth_developer, academy_builder, high_potential_preference, youngster_preference, data_reliance)
VALUES ('e0260000-0000-4000-8000-000000000007', TRUE, TRUE, TRUE, 86, 84, 75)
ON CONFLICT DO NOTHING;

INSERT INTO public.staff_members (id, slug, full_name, known_as, date_of_birth, country, biography, primary_role, secondary_roles, current_real_team_id, real_contract_end_year, reputation, current_ability, potential_ability, experience_years, salary_expectation, compensation_cost, ambition, loyalty, adaptability, learning_rate, development_phase, retirement_age, personality, coaching_philosophy, preferred_team_strategy, is_available, is_generated, is_active, batting_coaching, pace_bowling_coaching, spin_bowling_coaching, fielding_coaching, wicketkeeping_coaching, technical_coaching, tactical_knowledge, player_development, youth_development, judging_ability, judging_potential, man_management, motivation, profile_confidence, rating_basis)
VALUES ('e0260000-0000-4000-8000-000000000008', 'jonty-rhodes', 'Jonty Rhodes', 'Jonty Rhodes', '1969-07-27', 'South Africa', 'Renowned fielding specialist with Mumbai Indians, Punjab Kings and Lucknow Super Giants coaching experience.', 'fielding_coach', ARRAY['mentor', 'coach']::text[], NULL, NULL, 90, 83, 84, 16, 18500000, 0, 75, 73, 84, 68, 'peak', 70, 'energetic', 'development', 'Aggressive', TRUE, FALSE, TRUE, 11, 5, 5, 20, 10, 18, 15, 18, 17, 16, 16, 18, 19, 'medium', 'Long-running IPL fielding appointments and specialist reputation support elite fielding; no unsupported 2026 IPL contract is assumed.')
ON CONFLICT DO NOTHING;

INSERT INTO public.staff_traits (staff_id, fielding_specialist, elite_motivator, youth_developer, player_favourite, youngster_preference, tactical_aggression, data_reliance)
VALUES ('e0260000-0000-4000-8000-000000000008', TRUE, TRUE, TRUE, TRUE, 78, 75, 57)
ON CONFLICT DO NOTHING;

INSERT INTO public.staff_members (id, slug, full_name, known_as, date_of_birth, country, biography, primary_role, secondary_roles, current_real_team_id, real_contract_end_year, reputation, current_ability, potential_ability, experience_years, salary_expectation, compensation_cost, ambition, loyalty, adaptability, learning_rate, development_phase, retirement_age, personality, coaching_philosophy, preferred_team_strategy, is_available, is_generated, is_active, batting_coaching, pace_bowling_coaching, spin_bowling_coaching, fielding_coaching, wicketkeeping_coaching, technical_coaching, tactical_knowledge, player_development, youth_development, judging_ability, judging_potential, man_management, motivation, profile_confidence, rating_basis)
VALUES ('e0260000-0000-4000-8000-000000000009', 'ravi-shastri', 'Ravi Shastri', 'Ravi Shastri', '1962-05-27', 'India', 'Former India men''s head coach and prominent commentator, valued for senior-player management and high-pressure leadership.', 'head_coach', ARRAY['mentor', 'coach']::text[], NULL, NULL, 94, 86, 86, 8, 25000000, 0, 68, 70, 77, 64, 'peak', 70, 'charismatic', 'attacking', 'Aggressive', TRUE, FALSE, TRUE, 14, 8, 11, 10, 4, 15, 19, 16, 12, 18, 15, 19, 20, 'medium', 'Successful India head-coach tenure supports top-tier leadership and motivation; availability is an in-game market assumption, not a claimed current appointment.')
ON CONFLICT DO NOTHING;

INSERT INTO public.staff_traits (staff_id, elite_man_manager, elite_motivator, big_game_coach, pressure_specialist, star_player_preference, veteran_preference, tactical_aggression)
VALUES ('e0260000-0000-4000-8000-000000000009', TRUE, TRUE, TRUE, TRUE, 83, 77, 81)
ON CONFLICT DO NOTHING;

INSERT INTO public.staff_members (id, slug, full_name, known_as, date_of_birth, country, biography, primary_role, secondary_roles, current_real_team_id, real_contract_end_year, reputation, current_ability, potential_ability, experience_years, salary_expectation, compensation_cost, ambition, loyalty, adaptability, learning_rate, development_phase, retirement_age, personality, coaching_philosophy, preferred_team_strategy, is_available, is_generated, is_active, batting_coaching, pace_bowling_coaching, spin_bowling_coaching, fielding_coaching, wicketkeeping_coaching, technical_coaching, tactical_knowledge, player_development, youth_development, judging_ability, judging_potential, man_management, motivation, profile_confidence, rating_basis)
VALUES ('e0260000-0000-4000-8000-000000000010', 'chris-silverwood', 'Chris Silverwood', 'Chris Silverwood', '1975-03-05', 'England', 'Former England and Sri Lanka men''s head coach with a pace-bowling background; left the Sri Lanka post in 2024.', 'head_coach', ARRAY['pace_bowling_coach', 'assistant_coach']::text[], NULL, NULL, 81, 82, 83, 15, 16500000, 0, 78, 71, 80, 70, 'peak', 69, 'calm', 'technical', 'Adaptive', TRUE, FALSE, TRUE, 8, 18, 8, 10, 4, 17, 18, 16, 15, 17, 16, 17, 17, 'medium', 'England and Sri Lanka head-coaching jobs plus earlier England pace role support both leadership and pace ratings.')
ON CONFLICT DO NOTHING;

INSERT INTO public.staff_traits (staff_id, pace_specialist, senior_developer, pitch_adaptation_specialist, tactical_aggression, data_reliance, squad_rotation_preference)
VALUES ('e0260000-0000-4000-8000-000000000010', TRUE, TRUE, TRUE, 62, 68, 66)
ON CONFLICT DO NOTHING;

INSERT INTO public.staff_members (id, slug, full_name, known_as, date_of_birth, country, biography, primary_role, secondary_roles, current_real_team_id, real_contract_end_year, reputation, current_ability, potential_ability, experience_years, salary_expectation, compensation_cost, ambition, loyalty, adaptability, learning_rate, development_phase, retirement_age, personality, coaching_philosophy, preferred_team_strategy, is_available, is_generated, is_active, batting_coaching, pace_bowling_coaching, spin_bowling_coaching, fielding_coaching, wicketkeeping_coaching, technical_coaching, tactical_knowledge, player_development, youth_development, judging_ability, judging_potential, man_management, motivation, profile_confidence, rating_basis)
VALUES ('e0260000-0000-4000-8000-000000000011', 'marcus-trescothick', 'Marcus Trescothick', 'Marcus Trescothick', '1975-12-25', 'England', 'England men''s batting and assistant coach, still involved with Brendon McCullum''s white-ball team in September 2026.', 'batting_coach', ARRAY['assistant_coach', 'head_coach']::text[], NULL, NULL, 84, 84, 85, 12, 17000000, 0, 77, 79, 77, 70, 'peak', 69, 'supportive', 'technical', 'Adaptive', TRUE, FALSE, TRUE, 19, 5, 7, 11, 4, 18, 17, 18, 16, 17, 17, 18, 17, 'medium', 'ECB elite batting role, interim white-ball leadership and continuing England staff presence support batting and management ratings.')
ON CONFLICT DO NOTHING;

INSERT INTO public.staff_traits (staff_id, batting_specialist, senior_developer, player_favourite, youngster_preference, tactical_aggression, data_reliance)
VALUES ('e0260000-0000-4000-8000-000000000011', TRUE, TRUE, TRUE, 75, 72, 67)
ON CONFLICT DO NOTHING;

INSERT INTO public.staff_members (id, slug, full_name, known_as, date_of_birth, country, biography, primary_role, secondary_roles, current_real_team_id, real_contract_end_year, reputation, current_ability, potential_ability, experience_years, salary_expectation, compensation_cost, ambition, loyalty, adaptability, learning_rate, development_phase, retirement_age, personality, coaching_philosophy, preferred_team_strategy, is_available, is_generated, is_active, batting_coaching, pace_bowling_coaching, spin_bowling_coaching, fielding_coaching, wicketkeeping_coaching, technical_coaching, tactical_knowledge, player_development, youth_development, judging_ability, judging_potential, man_management, motivation, profile_confidence, rating_basis)
VALUES ('e0260000-0000-4000-8000-000000000012', 'sarah-taylor', 'Sarah Taylor', 'Sarah Taylor', '1989-05-20', 'England', 'Specialist wicketkeeping coach who has worked with men''s teams and is on England''s September 2026 white-ball coaching staff.', 'wicketkeeping_coach', ARRAY['fielding_coach', 'coach']::text[], NULL, NULL, 82, 81, 86, 6, 14000000, 0, 82, 78, 82, 84, 'developing', 68, 'analytical', 'technical', 'Adaptive', TRUE, FALSE, TRUE, 12, 4, 5, 18, 20, 18, 14, 17, 18, 17, 18, 16, 17, 'medium', 'Elite wicketkeeping career and demonstrated men''s specialist coaching justify elite keeping and fielding, with growing wider coaching ability.')
ON CONFLICT DO NOTHING;

INSERT INTO public.staff_traits (staff_id, wicketkeeping_specialist, fielding_specialist, youth_developer, high_potential_preference, youngster_preference, data_reliance)
VALUES ('e0260000-0000-4000-8000-000000000012', TRUE, TRUE, TRUE, 83, 82, 73)
ON CONFLICT DO NOTHING;
