alter table public.players
  add column if not exists date_of_birth date,
  add column if not exists ipl_batting_innings integer not null default 0,
  add column if not exists ipl_not_outs integer not null default 0,
  add column if not exists ipl_balls_faced integer not null default 0,
  add column if not exists ipl_fifties integer not null default 0,
  add column if not exists ipl_hundreds integer not null default 0,
  add column if not exists ipl_high_score integer not null default 0,
  add column if not exists ipl_fours integer not null default 0,
  add column if not exists ipl_sixes integer not null default 0,
  add column if not exists ipl_bowling_balls integer not null default 0,
  add column if not exists ipl_runs_conceded integer not null default 0,
  add column if not exists ipl_best_bowling_wickets integer not null default 0,
  add column if not exists ipl_best_bowling_runs integer not null default 0,
  add column if not exists ipl_four_wicket_hauls integer not null default 0,
  add column if not exists ipl_five_wicket_hauls integer not null default 0,
  add column if not exists ipl_catches integer not null default 0,
  add column if not exists ipl_stumpings integer not null default 0,
  add column if not exists ipl_run_outs integer not null default 0,
  add column if not exists guaranteed_staff_conversion boolean not null default false,
  add column if not exists injury_proneness integer check (injury_proneness between 0 and 100),
  add column if not exists fitness integer check (fitness between 0 and 100),
  add column if not exists stamina integer check (stamina between 0 and 100),
  add column if not exists consistency integer check (consistency between 0 and 100),
  add column if not exists big_match_rating integer check (big_match_rating between 0 and 100),
  add column if not exists pressure_rating integer check (pressure_rating between 0 and 100),
  add column if not exists fielding_rating integer check (fielding_rating between 0 and 100),
  add column if not exists wicketkeeping_rating integer check (wicketkeeping_rating between 0 and 100),
  add column if not exists pace_rating integer check (pace_rating between 0 and 100),
  add column if not exists spin_rating integer check (spin_rating between 0 and 100),
  add column if not exists powerplay_batting integer check (powerplay_batting between 0 and 100),
  add column if not exists middle_overs_batting integer check (middle_overs_batting between 0 and 100),
  add column if not exists death_batting integer check (death_batting between 0 and 100),
  add column if not exists powerplay_bowling integer check (powerplay_bowling between 0 and 100),
  add column if not exists middle_overs_bowling integer check (middle_overs_bowling between 0 and 100),
  add column if not exists death_bowling integer check (death_bowling between 0 and 100),
  add column if not exists preferred_batting_position integer check (preferred_batting_position between 1 and 11),
  add column if not exists state text,
  add column if not exists international_debut_date date,
  add column if not exists international_caps integer not null default 0 check (international_caps >= 0),
  add column if not exists leadership integer check (leadership between 0 and 100),
  add column if not exists professionalism integer check (professionalism between 0 and 100),
  add column if not exists loyalty integer check (loyalty between 0 and 100),
  add column if not exists retirement_age integer check (retirement_age between 25 and 60);

comment on column public.players.date_of_birth is
  'Player date of birth used to derive age against the in-game career date.';

comment on column public.players.guaranteed_staff_conversion is
  'When true, the player must be converted into a staff candidate after retirement.';
