import { supabase } from "./client";
import { Team, FanBase, AIPersonality } from "../types";

const STATIC_TEAMS: Team[] = [
  {
    id: "MI",
    name: "Mumbai Indians",
    shortName: "MI",
    primaryColor: "#004BA0",
    secondaryColor: "#D1AB3E",
    homeGround: "Wankhede Stadium",
    city: "Mumbai",
    totalPurse: 12000,
    spentAmount: 0,
    remainingPurse: 12000,
    squad: [],
    retainedPlayers: [],
    rtmCardsUsed: 0,
    rtmCardsTotal: 6,
    maxSquadSize: 25,
    minSquadSize: 18,
    overseasPlayersCurrent: 0,
    overseasPlayersMax: 8,
    fanBase: "Massive" as any,
    prestige: 10,
    aiPersonality: "Aggressive" as any,
    dna: {
      loyalty: 78,
      prefYoungsters: 89,
      experienceFocus: 67,
      bigNamesPref: 87,
      looksForDepth: 40,
      alrValue: 95,
      batValue: 80,
      bowlValue: 65,
      commitmentToTargets: 80,
      segmentFocus: {
        overseasPacers: 85,
        indianPacers: 70,
        overseasSpinners: 35,
        indianSpinners: 40,
        overseasAllRounders: 75,
        indianAllRounders: 85,
        overseasBatters: 70,
        indianBatters: 85,
      },
    },
  },
  {
    id: "CSK",
    name: "Chennai Super Kings",
    shortName: "CSK",
    primaryColor: "#FDB913",
    secondaryColor: "#141414",
    homeGround: "MA Chidambaram Stadium",
    city: "Chennai",
    totalPurse: 12000,
    spentAmount: 0,
    remainingPurse: 12000,
    squad: [],
    retainedPlayers: [],
    rtmCardsUsed: 0,
    rtmCardsTotal: 6,
    maxSquadSize: 25,
    minSquadSize: 18,
    overseasPlayersCurrent: 0,
    overseasPlayersMax: 8,
    fanBase: "Massive" as any,
    prestige: 10,
    aiPersonality: "Conservative" as any,
    dna: {
      loyalty: 93,
      prefYoungsters: 44,
      experienceFocus: 90,
      bigNamesPref: 80,
      looksForDepth: 88,
      alrValue: 75,
      batValue: 65,
      bowlValue: 50,
      commitmentToTargets: 87,
      segmentFocus: {
        overseasPacers: 75,
        indianPacers: 75,
        overseasSpinners: 65,
        indianSpinners: 80,
        overseasAllRounders: 80,
        indianAllRounders: 90,
        overseasBatters: 70,
        indianBatters: 70,
      },
    },
  },
  {
    id: "KKR",
    name: "Kolkata Knight Riders",
    shortName: "KKR",
    primaryColor: "#3B215F",
    secondaryColor: "#D4A017",
    homeGround: "Eden Gardens",
    city: "Kolkata",
    totalPurse: 12000,
    spentAmount: 0,
    remainingPurse: 12000,
    squad: [],
    retainedPlayers: [],
    rtmCardsUsed: 0,
    rtmCardsTotal: 6,
    maxSquadSize: 25,
    minSquadSize: 18,
    overseasPlayersCurrent: 0,
    overseasPlayersMax: 8,
    fanBase: "Large" as any,
    prestige: 9,
    aiPersonality: "Balanced" as any,
    dna: {
      loyalty: 83,
      prefYoungsters: 68,
      experienceFocus: 55,
      bigNamesPref: 86,
      looksForDepth: 80,
      alrValue: 90,
      batValue: 75,
      bowlValue: 75,
      commitmentToTargets: 75,
      segmentFocus: {
        overseasPacers: 65,
        indianPacers: 65,
        overseasSpinners: 85,
        indianSpinners: 85,
        overseasAllRounders: 95,
        indianAllRounders: 75,
        overseasBatters: 60,
        indianBatters: 80,
      },
    },
  },
  {
    id: "RCB",
    name: "Royal Challengers Bengaluru",
    shortName: "RCB",
    primaryColor: "#DA1818",
    secondaryColor: "#D4A017",
    homeGround: "M. Chinnaswamy Stadium",
    city: "Bengaluru",
    totalPurse: 12000,
    spentAmount: 0,
    remainingPurse: 12000,
    squad: [],
    retainedPlayers: [],
    rtmCardsUsed: 0,
    rtmCardsTotal: 6,
    maxSquadSize: 25,
    minSquadSize: 18,
    overseasPlayersCurrent: 0,
    overseasPlayersMax: 8,
    fanBase: "Massive" as any,
    prestige: 8,
    aiPersonality: "Aggressive" as any,
    dna: {
      loyalty: 60,
      prefYoungsters: 58,
      experienceFocus: 74,
      bigNamesPref: 96,
      looksForDepth: 40,
      alrValue: 60,
      batValue: 90,
      bowlValue: 59,
      commitmentToTargets: 45,
      segmentFocus: {
        overseasPacers: 80,
        indianPacers: 60,
        overseasSpinners: 30,
        indianSpinners: 55,
        overseasAllRounders: 60,
        indianAllRounders: 60,
        overseasBatters: 95,
        indianBatters: 90,
      },
    },
  },
  {
    id: "DC",
    name: "Delhi Capitals",
    shortName: "DC",
    primaryColor: "#17449B",
    secondaryColor: "#ffffff",
    homeGround: "Arun Jaitley Stadium",
    city: "Delhi",
    totalPurse: 12000,
    spentAmount: 0,
    remainingPurse: 12000,
    squad: [],
    retainedPlayers: [],
    rtmCardsUsed: 0,
    rtmCardsTotal: 6,
    maxSquadSize: 25,
    minSquadSize: 18,
    overseasPlayersCurrent: 0,
    overseasPlayersMax: 8,
    fanBase: "Large" as any,
    prestige: 7,
    aiPersonality: "Balanced" as any,
    dna: {
      loyalty: 50,
      prefYoungsters: 30,
      experienceFocus: 80,
      bigNamesPref: 75,
      looksForDepth: 74,
      alrValue: 65,
      batValue: 55,
      bowlValue: 80,
      commitmentToTargets: 60,
      segmentFocus: {
        overseasPacers: 80,
        indianPacers: 65,
        overseasSpinners: 55,
        indianSpinners: 75,
        overseasAllRounders: 65,
        indianAllRounders: 70,
        overseasBatters: 70,
        indianBatters: 60,
      },
    },
  },
  {
    id: "SRH",
    name: "Sunrisers Hyderabad",
    shortName: "SRH",
    primaryColor: "#F26522",
    secondaryColor: "#000000",
    homeGround: "Rajiv Gandhi International Cricket Stadium",
    city: "Hyderabad",
    totalPurse: 12000,
    spentAmount: 0,
    remainingPurse: 12000,
    squad: [],
    retainedPlayers: [],
    rtmCardsUsed: 0,
    rtmCardsTotal: 6,
    maxSquadSize: 25,
    minSquadSize: 18,
    overseasPlayersCurrent: 0,
    overseasPlayersMax: 8,
    fanBase: "Large" as any,
    prestige: 7,
    aiPersonality: "Aggressive" as any,
    dna: {
      loyalty: 70,
      prefYoungsters: 83,
      experienceFocus: 55,
      bigNamesPref: 65,
      looksForDepth: 70,
      alrValue: 75,
      batValue: 91,
      bowlValue: 45,
      commitmentToTargets: 67,
      segmentFocus: {
        overseasPacers: 75,
        indianPacers: 55,
        overseasSpinners: 45,
        indianSpinners: 65,
        overseasAllRounders: 70,
        indianAllRounders: 70,
        overseasBatters: 90,
        indianBatters: 70,
      },
    },
  },
  {
    id: "PBKS",
    name: "Punjab Kings",
    shortName: "PBKS",
    primaryColor: "#DD1F2D",
    secondaryColor: "#A7A9AC",
    homeGround: "Punjab Cricket Association Stadium",
    city: "Mohali",
    totalPurse: 12000,
    spentAmount: 0,
    remainingPurse: 12000,
    squad: [],
    retainedPlayers: [],
    rtmCardsUsed: 0,
    rtmCardsTotal: 6,
    maxSquadSize: 25,
    minSquadSize: 18,
    overseasPlayersCurrent: 0,
    overseasPlayersMax: 8,
    fanBase: "Medium" as any,
    prestige: 6,
    aiPersonality: "Balanced" as any,
    dna: {
      loyalty: 38,
      prefYoungsters: 55,
      experienceFocus: 77,
      bigNamesPref: 68,
      looksForDepth: 45,
      alrValue: 76,
      batValue: 45,
      bowlValue: 30,
      commitmentToTargets: 30,
      segmentFocus: {
        overseasPacers: 75,
        indianPacers: 60,
        overseasSpinners: 45,
        indianSpinners: 40,
        overseasAllRounders: 75,
        indianAllRounders: 60,
        overseasBatters: 70,
        indianBatters: 85,
      },
    },
  },
  {
    id: "RR",
    name: "Rajasthan Royals",
    shortName: "RR",
    primaryColor: "#EA1A85",
    secondaryColor: "#ffffff",
    homeGround: "Sawai Mansingh Stadium",
    city: "Jaipur",
    totalPurse: 12000,
    spentAmount: 0,
    remainingPurse: 12000,
    squad: [],
    retainedPlayers: [],
    rtmCardsUsed: 0,
    rtmCardsTotal: 6,
    maxSquadSize: 25,
    minSquadSize: 18,
    overseasPlayersCurrent: 0,
    overseasPlayersMax: 8,
    fanBase: "Medium" as any,
    prestige: 7,
    aiPersonality: "Conservative" as any,
    dna: {
      loyalty: 80,
      prefYoungsters: 88,
      experienceFocus: 26,
      bigNamesPref: 46,
      looksForDepth: 70,
      alrValue: 65,
      batValue: 81,
      bowlValue: 85,
      commitmentToTargets: 67,
      segmentFocus: {
        overseasPacers: 90,
        indianPacers: 85,
        overseasSpinners: 60,
        indianSpinners: 75,
        overseasAllRounders: 55,
        indianAllRounders: 70,
        overseasBatters: 50,
        indianBatters: 85,
      },
    },
  },
  {
    id: "GT",
    name: "Gujarat Titans",
    shortName: "GT",
    primaryColor: "#1B2133",
    secondaryColor: "#ffffff",
    homeGround: "Narendra Modi Stadium",
    city: "Ahmedabad",
    totalPurse: 12000,
    spentAmount: 0,
    remainingPurse: 12000,
    squad: [],
    retainedPlayers: [],
    rtmCardsUsed: 0,
    rtmCardsTotal: 6,
    maxSquadSize: 25,
    minSquadSize: 18,
    overseasPlayersCurrent: 0,
    overseasPlayersMax: 8,
    fanBase: "Large" as any,
    prestige: 8,
    aiPersonality: "Balanced" as any,
    dna: {
      loyalty: 70,
      prefYoungsters: 60,
      experienceFocus: 55,
      bigNamesPref: 50,
      looksForDepth: 88,
      alrValue: 50,
      batValue: 80,
      bowlValue: 90,
      commitmentToTargets: 75,
      segmentFocus: {
        overseasPacers: 85,
        indianPacers: 95,
        overseasSpinners: 75,
        indianSpinners: 75,
        overseasAllRounders: 45,
        indianAllRounders: 65,
        overseasBatters: 60,
        indianBatters: 85,
      },
    },
  },
  {
    id: "LSG",
    name: "Lucknow Super Giants",
    shortName: "LSG",
    primaryColor: "#0057e2",
    secondaryColor: "#ffffff",
    homeGround: "BRSABV Ekana Cricket Stadium",
    city: "Lucknow",
    totalPurse: 12000,
    spentAmount: 0,
    remainingPurse: 12000,
    squad: [],
    retainedPlayers: [],
    rtmCardsUsed: 0,
    rtmCardsTotal: 6,
    maxSquadSize: 25,
    minSquadSize: 18,
    overseasPlayersCurrent: 0,
    overseasPlayersMax: 8,
    fanBase: "Medium" as any,
    prestige: 6,
    aiPersonality: "Aggressive" as any,
    dna: {
      loyalty: 20,
      prefYoungsters: 61,
      experienceFocus: 60,
      bigNamesPref: 50,
      looksForDepth: 80,
      alrValue: 70,
      batValue: 65,
      bowlValue: 90,
      commitmentToTargets: 70,
      segmentFocus: {
        overseasPacers: 40,
        indianPacers: 90,
        overseasSpinners: 40,
        indianSpinners: 70,
        overseasAllRounders: 70,
        indianAllRounders: 70,
        overseasBatters: 90,
        indianBatters: 55,
      },
    },
  },
];

let serverCachedTeams: Team[] | null = null;
let clientCachedTeams: Team[] | null = null;

export async function fetchTeamsFromSupabase(forceRefresh = false): Promise<Team[]> {
  try {
    // If running in browser context, call our Next.js API route wrapper
    if (typeof window !== "undefined") {
      if (clientCachedTeams && !forceRefresh) {
        return clientCachedTeams;
      }
      const res = await fetch("/api/teams");
      if (!res.ok) throw new Error("Browser API fetch teams failed");
      const data = await res.json();
      clientCachedTeams = data;
      return data;
    }

    if (serverCachedTeams && !forceRefresh) {
      return serverCachedTeams;
    }

    if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY) {
      throw new Error("Missing Supabase credentials");
    }

    const { data, error } = await supabase
      .from("teams")
      .select("*")
      .order("prestige", { ascending: false });

    if (error) throw error;

    const mapped = data.map((row: any): Team => {
      const totalPurse = Number(row.total_purse) || 0;
      return {
        id: row.id,
        name: row.name,
        shortName: row.short_name,
        primaryColor: row.primary_color,
        secondaryColor: row.secondary_color,
        homeGround: row.home_ground,
        city: row.city,
        totalPurse,
        spentAmount: 0,
        remainingPurse: totalPurse,
        squad: [],
        retainedPlayers: [],
        rtmCardsUsed: 0,
        rtmCardsTotal: Number(row.rtm_cards_total) || 0,
        maxSquadSize: Number(row.max_squad_size) || 0,
        minSquadSize: Number(row.min_squad_size) || 0,
        overseasPlayersCurrent: 0,
        overseasPlayersMax: Number(row.overseas_players_max) || 0,
        fanBase: row.fan_base as FanBase,
        prestige: Number(row.prestige) || 0,
        aiPersonality: row.ai_personality as AIPersonality,
        dna: {
          loyalty: Number(row.dna_loyalty) || 0,
          prefYoungsters: Number(row.dna_pref_youngsters) || 0,
          experienceFocus: Number(row.dna_experience_focus) || 0,
          bigNamesPref: Number(row.dna_big_names_pref) || 0,
          looksForDepth: Number(row.dna_looks_for_depth) || 0,
          alrValue: Number(row.dna_alr_value) || 0,
          batValue: Number(row.dna_bat_value) || 0,
          bowlValue: Number(row.dna_bowl_value) || 0,
          commitmentToTargets: Number(row.dna_commitment_to_targets) || 0,
          segmentFocus: {
            overseasPacers: Number(row.sf_overseas_pacers) || 0,
            indianPacers: Number(row.sf_indian_pacers) || 0,
            overseasSpinners: Number(row.sf_overseas_spinners) || 0,
            indianSpinners: Number(row.sf_indian_spinners) || 0,
            overseasAllRounders: Number(row.sf_overseas_all_rounders) || 0,
            indianAllRounders: Number(row.sf_indian_all_rounders) || 0,
            overseasBatters: Number(row.sf_overseas_batters) || 0,
            indianBatters: Number(row.sf_indian_batters) || 0,
          },
        },
      };
    });

    serverCachedTeams = mapped;
    return mapped;
  } catch (error) {
    console.warn("Supabase fetch teams failed, using static teams configuration:", error);
    return STATIC_TEAMS;
  }
}
